### ISSUE TITLE
Security check

### ISSUE THREAD

**Issue by alexandrVakhtinTari** [tari-project/wallet-android#1005]
https://book.hacktricks.xyz/mobile-pentesting/android-app-pentesting/bypass-biometric-authentication-android

There is a site with a description of security weaknesses. Need to check whether applicable something on our case or not

**Comment by igordanilcenko** [comment]
After a discussion with @TruszczynskiA I'll revert the fix of multiple app tasks

**Comment by igordanilcenko** [comment]
Need to verify the scenarios again. Want to test some of old version to confirm the issues were present and then test the latest version to confirm that issues are gone
