### ISSUE TITLE
App stuck on the onboarding/loading screen

### ISSUE THREAD

**Issue by TruszczynskiA** [tari-project/wallet-android#1013]
We get an report when one of our users can't pass the onboarding flow. The app is stuck on the "We're creating your wallet" page.

![Image](https://github.com/tari-project/wallet-android/assets/6376351/a3dc4156-3f7e-4703-bbbd-e9266fa36ec4)

**Comment by igordanilcenko** [comment]
Waiting for a new version of FFI lib to fix
