### ISSUE TITLE
[QA tested] Users are unable to delete contact from their contact book on Aurora

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/wallet-android#1114]
User are unable to delete contacts. When they delete a contact on the Aurora App and they redirect back to the contact book the contact/s appear there again. They can try to repeat the process but the contact/s keep on appearing on the contact book after it was deleted.

This is on a Xiaomi Redmi Note 10 Android device.

I was unable to get a video of this because of a crash issue I experienced but as soon as the app it working again I'll make a video and add it in here.

Build: Bitrise (293) version

Video: https://drive.google.com/file/d/1oCJdwMf7zyjHpxzZFITipaVCG23XEqgR/view?usp=sharing

**Comment by igordanilcenko** [comment]
Fixed in `0.26.1(295)` version

**Comment by Anziskavds** [comment]
Tested successfully on build 295. I tested on a Xiaomi Redmi Note 10 on Android 13.

**Comment by Anziskavds** [comment]
I have noticed when the user exits the app and go back in the delete contact appears there again. https://drive.google.com/file/d/1FuURlpNvGAZOvci9hnQ0J4CM6usVQ12g/view?usp=sharing
