### ISSUE TITLE
[QA tested] Users are unable to Break UTXOs

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/wallet-android#1115]
When a user clicks on a UTXO and the click on the Break button, nothing happens. The user gets redirected back to the UTXO tile after clicking on the Break button. 

This is on an Xiaomi Redmi Note 10 Android 13 on the Bitrise (293) version.

Video: https://drive.google.com/file/d/1lFsEpPB5aQ1ZIv1I4ZFmEcxSZczr3y_n/view?usp=sharing

**Comment by igordanilcenko** [comment]
Fixed in the latest development build

**Comment by Anziskavds** [comment]
Verified that this is working on the current Android build (https://app.bitrise.io/app/a5c3eb49143b3bc5/build/7260289e-29d3-4c75-8185-388782133e71/artifact/decd7d9f6a6303a4/p/e4bdacb8ac70a0b1dc2e1bf63d8c9436).
