### ISSUE TITLE
[QA tested] Aurora app keeps stopping when the user tries to add or remove a contact as favorites

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/wallet-android#1116]
When a user tries to add or remove a contact as a favorite the app keeps on crashing/closing.

This is on a Xiaomi Redmi Note 10 on Android 13.

Build: Bitrise (293) version

Video: https://drive.google.com/file/d/1ilsJko1Ym-fEbsPvr8_gZhuso_-SNbEC/view?usp=sharing

**Comment by igordanilcenko** [comment]
Fixed in `0.26.1(295)` version

**Comment by Anziskavds** [comment]
I haven't experience any crashes on 0.26.1(295)version. Tested successfully on Xiaomi Redmin Note 10S on Android 13 on 0.26.1(295)version.
