### ISSUE TITLE
[QA tested] Users are unable to add contact to Aurora from their contacts

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/wallet-android#1117]
When a user clicks on the add contact button to add a contact to Aurora from their contacts, the user doesn't get any contacts to add to the Aurora app.

This is on a Xiaomi Redmin Note 10 on Android 13.

Build: Bitrise (293) version

Video: https://drive.google.com/file/d/1I9e0SNjtKunR7hiIQhUK5NPWya0FzHmK/view?usp=sharing

**Comment by igordanilcenko** [comment]
Try to retest it with the latest development version.
make sure you have the Contacts permission granted

**Comment by Cultmojo** [comment]
Tested this and it is still not working correctly. What I am seeing after a fresh install of build NextNet 0.26.1-libwallet-v1.0.0-rc.8 b300. 
Device info: 
Android 14; Pixel 7a Build/AP2A.240605.024

Steps to reproduce: 
1. Install app > go through on boarding steps which include enable access to Contacts
2. Verify in phone system settings Applications > Aurora > Permissions > Contacts Permission > Allow is enabled
3. Back in the Aurora app, navigate to Contacts screen and verify NO contacts are being imported from the phone contacts.
4. Go back to phone system settings Applications > Aurora > Permissions > Contacts Permission> and toggle the radio to Don't Allow and then back to Allow.
5. Go back to Aurora app and verify contacts are now being populated on the Contacts screen.

**Comment by igordanilcenko** [comment]
@Anziskavds I've investigated your video again. The screen you see after clicking on the Add Contacts button on the toolbar – it's the screen for adding a contact by entering its address manually, or by scanning a QR. It isn't a screen for selecting phonebook contacts, phonebook contacts are added automatically to the list of contacts after the user has granted the contacts permission

**Comment by igordanilcenko** [comment]
Should be fixed in the latest build

**Comment by Anziskavds** [comment]
This is working on the Esmeralda 0.26.1-libwallet-v1.3.o-pre.0 b302. Tested on a Xiaomi Redmi Note 10S on Chrome.
