### ISSUE TITLE
[QA tested] User are unable to send Tari to another user using the Aurora wallet address

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/wallet-android#1119]
When a user wants to send some Tari/Tokens to another user by using their Aurora wallet address by coping and pasting it in the input field, the app crashes on the sender.

This is on a Xiaomi Redmi Note 10S on Android 13.

This is on the Bitrise (293) version.

Video: https://drive.google.com/file/d/1i4Cw2lqZxqdyYgbJyr8AyY8luaADYpA4/view?usp=sharing

**Comment by igordanilcenko** [comment]
Fixed in `0.26.1(295)` version

**Comment by Anziskavds** [comment]
Tested successfully on a Xiaomi Redmi Note 10S on Android 13 on 0.26.1(295)version.
