### ISSUE TITLE
[QA tested] Aurora App on Android keeps on crashing 

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/wallet-android#1120]
When a user is busy on the app, the app keeps on crashing intermittently. User is not busy with something specific when the app crashes.

This is on a Xiaomi Redmi Note 10S on Android 13

This is on the bitrise (293) build

Video: https://drive.google.com/file/d/1lEsQhP6m02NU7I1CItX9dmPSx60L7D_B/view?usp=sharing

**Comment by igordanilcenko** [comment]
Fixed in `0.26.1(295)` version

**Comment by Anziskavds** [comment]
I haven't experience any crashes on 0.26.1(295)version. Tested successfully on Xiaomi Redmin Note 10S on Android 13 on 0.26.1(295)version.
