### ISSUE TITLE
"Add to Favorites" is not working

### ISSUE THREAD

**Issue by Cultmojo** [tari-project/wallet-android#1136]
build NextNet 0.26.1-libwallet-v1.0.0-rc.8 b300.
Device info:
Android 14; Pixel 7a Build/AP2A.240605.024

Description: When I try to add a contact to Favorites, the Add to Favorites button does not perform the action when tapped. Nothing happens. 

Steps to reproduce:
1. Go to Contacts
2. Select a phone contact
3. The Contact Profile screen should slide in > tap "Add to Favorites"
4. Verify that the contact was not added to favorites and that no action was performed. 

Expected behavior: 
When the "Add to favorites" is tapped, the contact should be visible on the Favorites tab

**Comment by igordanilcenko** [comment]
Duplicates #1171
