### ISSUE TITLE
The Add new Contact text box reads"Enter Emoji ID, Contact Name or Yat" but only accepts Emoji ID

### ISSUE THREAD

**Issue by ghost** [tari-project/wallet-android#1168]
Description:
The Add new Contact text box reads"Enter Emoji ID, Contact Name or Yat" but only accepts Emoji ID

Steps to reproduce:
1. Go to contacts and click the add Contact icon
2. Verify that the text box says "Enter Emoji ID, Contact Name or Yat" 
3. Verify the text box only accepts Emoji ID wallet addresses

Android v14, Google Pixel 7a
Aurora: 0.26.1-libwallet-v1.3.0-pre.0

**Comment by igordanilcenko** [comment]
It won't be actual when the Yat feature has been implemented properly.

**Comment by igordanilcenko** [comment]
Will be fixed once #1118 is fixed
