### ISSUE TITLE
Cannot read console wallet QR code

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/wallet-android#1175]
Trying to send to console wallet qr code, does not read the the console wallet qr code
![Screenshot 2024-09-03 at 11 38 33](https://github.com/user-attachments/assets/383295fd-c601-4a94-8895-8a9f40272d79)

**Comment by igordanilcenko** [comment]
The given QR isn't readable by any QR-scanners, so the problem isn't in the app, but in the image
