### ISSUE TITLE
Wallet displaying invalid 0 balances despite having funds

### ISSUE THREAD

**Issue by therealdannzor** [tari-project/wallet-android#1180]
I see the message `Not enough tXTR in your available balance` when trying to send another transaction while another one is still pending. It is also calculates the fee for a very long time.

**Comment by laalauren1** [comment]
@therealdannzor Has your issue already been escalated?

**Comment by igordanilcenko** [comment]
I'll try to investigate the loading time.
But about the available balance – I think it's correct since UTXO isn't available to spend until the prev tx is ongoing.

**Comment by Anziskavds** [comment]
Tested successfully on Xiaomi Redmi Note 10 on Nextnet 0.28.1-libwallet-v1.8.0-rc.0 b315.
