### ISSUE TITLE
Transaction could not be sent

### ISSUE THREAD

**Issue by hansieodendaal** [tari-project/wallet-android#1181]
First transaction sent to 

f4PSJ3hQdHepXchAgA7babXVrwQUQC5KoajJbRkBx8WBQpSxJYVHVKzJE7B5vyDyYCCMN9AqizFCiYtWbHjY7PxwqvW

successful, next tranaction to 

🍗🌊🍉🚗🍵🎷🙈😍🏭🍈😂🦂🏈👍💣💐📷😈🚂🎼💩🐮🍈🚂🍸🍺📜⭐📌🚀📿🐺👠🎈💻🎈💡👕🌕💎👖🍆🏭🐸🔑🌊😷💻🔫🏭📜🌽💊🍔🍋🦆🤖🍌🚂😈🎯🍫🍸💈👖🐔🐚

not successful twice, succeeded on the 3rd try

**Comment by igordanilcenko** [comment]
Probably connected with #1248
