### ISSUE TITLE
Missing plain text note in transaction

### ISSUE THREAD

**Issue by therealdannzor** [tari-project/wallet-android#1182]
I sent a successful but pending transaction to someone and my note disappeared. I chose the expedited transaction (potentially less private) for faster finality. I was able to receive a transaction with a gif as note.

**Comment by therealdannzor** [comment]
The transaction was 5 tXTR to recipient
```
🍗🌊🍉🦀🚚🎼🚧🚿🎳🎠🚪💔🌊🔌🐐🐝🎼👑🚽🎿🐞🚂😎🎁🎻🎮🎰🔭💵🐋🤑🍓🦀🌲💐🐴🦁🌊🐛🍇🥑💈🐍🎢🚓🍾👾📌🚗🏥🐮👟🛵🐛🔭💼📟🐼🎓🐶🐑🌙🎤🏀🎉🍐🎠
```

**Comment by Anziskavds** [comment]
Tested successfully on Xiaomi Redmi Note 10S on Esmeralda 0.26.1-libwallet-v1.4.0-pre.0 b302.
