### ISSUE TITLE
App says "Available to spend: 0" but can spend funds

### ISSUE THREAD

**Issue by mrnaveira** [tari-project/wallet-android#1183]
Seems like a UI issue

Steps to reproduce:
* Receive some funds
* Wait for the transaction to finish (payment received)
* On the main screen, "Available to spend: 0,00" but I was able to send funds to other wallets
* Eventually, some minutes later, the  "Available to spend" counter did reflect the amount

**Comment by igordanilcenko** [comment]
Duplicates #1238

**Comment by Anziskavds** [comment]
Tested successfully on Xiaomi Redmi Note 10 on Nextnet 0.28.1-libwallet-v1.8.0-rc.0 b315.
