### ISSUE TITLE
Invalid transaction stage message on transaction details

### ISSUE THREAD

**Issue by mrnaveira** [tari-project/wallet-android#1184]
Seems like a minor UI issue.

Steps to reproduce:
* Receive some funds
* The first step in the transaction is "Completing final processing (1 of **4**)", but if I go to transaction details, it says "Completing final processing (1 of **1**)", which does not match
* After the transaction goes to step 2, then the message is valid in the transaction details: "Completing final processing (2 of 4)", so it seems like a minor UI issues on the first step of a transaction in the transaction details screen

**Comment by igordanilcenko** [comment]
Probably duplicates [#1151](https://github.com/tari-project/wallet-android/issues/1151)

**Comment by igordanilcenko** [comment]
Merged two issues. Here is the desc from another one: 

Sometimes txs on the Home Page are not refreshed properly and if the user clicks on it, it shows outdated data (see "steps 3 of 1")

<img src="https://github.com/user-attachments/assets/3433d33e-097a-42ab-9d8f-8269b7a669dd" width="350" />

**Comment by Anziskavds** [comment]
The two statuses show the same text but when a user click on the transaction the "steps" no longer shows. The steps only shows on the transaction history screen.![Image](https://github.com/user-attachments/assets/b3ce8169-4244-4da8-98da-e4ba997e9935)
![Image](https://github.com/user-attachments/assets/8f6fff78-4cc8-4b75-87eb-9fdd92b10bf2)
