### ISSUE TITLE
Paper wallet: Create a wallet from PW.

### ISSUE THREAD

**Issue by TruszczynskiA** [tari-project/wallet-android#1210]
The user should be able to "convert" the paper wallet into the Aurora wallet. To do that, the only thing that the user needs to do is to scan a paper wallet's QR code and confirm the action.

**Definition of done:**
- The user is able to "create" the wallet after scanning the paper wallet's QR code.
- The tokens stored on the paper wallet are visible to the user.

**Comment by igordanilcenko** [comment]
Implemented and tested
