### ISSUE TITLE
Paper wallet: replacing the existing wallet

### ISSUE THREAD

**Issue by TruszczynskiA** [tari-project/wallet-android#1217]
The user should be able to replace his existing wallet with a paper wallet by scanning the QR code.

**Definition of done:**
- The user can "recover" PW by scanning the QR code after he already have the wallet. The recovered wallet should replace the existing one.
- The user should be able to choose between transferring tokens from the PW to his main wallet or replacing his wallet with a paper wallet.

**Comment by igordanilcenko** [comment]
Implemented and tested
