### ISSUE TITLE
Wallet address doesn't show on My Profile screen

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/wallet-android#1220]
**Description:**
When the user clicks on the wallet icon on the home screen to view their full wallet address, there is no wallet address displaying in the box in their Profile.

**Steps to reproduce:**
1. Click on the wallet icon on the home screen
2. User redirects to their Profile screen
3. There is no wallet address displaying in the wallet address box

**Expected behaviour:**
User should see their wallet addresss displaying on the my profile screen in the wallet address box

**Device & App version:**
Xiaomi Redmi Note 10 on Android 13 on Aurora Nextnet 0.27.1-libwallet-v1.4.1-rc.0 b306

**Screenshot:**
![photo_2024-10-03 15 42 24](https://github.com/user-attachments/assets/0590b4c4-fe53-447c-a786-c80e81ea142d)

**Comment by igordanilcenko** [comment]
Done in the latest version
