### ISSUE TITLE
Restore wallet with seed phrase doesn't restore the users available Tari balance

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/wallet-android#1221]
**Description:**
When a user restores their wallet with seed phrase the avaialble Tari balance they had on the previous build didn't restore with the new wallet. The user lost all their Tari when they restored the app.

**Steps to reproduce:**
1. Install a new version of the App
2. Click on the Restore wallet button on the start up screen
3. Click on the seed phrase option
4. Enter the seed phrase
5. Click on the Restore wallet button
6. User get the secure wallet process
7. Complete the secure wallet process
8. User redirects to the home screen
9. The users balance is on 0 and it was 1.499 Tari on the previous build

**Expected behaviour:**
When a user restores their wallet the available Tari on their previous wallet should restore with the new wallet build

Device & App version:
Xiaomi Redmi Note 10 on Android 13 on Aurora Nextnet 0.27.1-libwallet-v1.4.1-rc.0 b306

Screenshot:
![photo_2024-10-03 16 28 53](https://github.com/user-attachments/assets/fbbb1815-51ec-4989-bb0c-599e7578c68d)

**Comment by igordanilcenko** [comment]
Can't reproduce it. All the funds are restored successfully
