### ISSUE TITLE
Restore wallet with seed phrase doesn't restore saved contacts

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/wallet-android#1222]
**Description:**
When a user restores their wallet with seed phrase the saved contacts they had on the previous build didn't restore with the new wallet. The user lost all their saved contacts when they restored the app.

**Steps to reproduce:**
1. Install a new version of the App
2. Click on the Restore wallet button on the start up screen
3. Click on the seed phrase option
4. Enter the seed phrase
5. Click on the Restore wallet button
6. User get the secure wallet process
7. Complete the secure wallet process
8. User redirects to the home screen
9. Click on the contacts button
10. None of the users saved contacts of the previous build saved/restored on the new build

**Expected behaviour:**
When a user restores their wallet the saved contacts on their previous wallet should restore with the new wallet build

**Device & App version:**
Xiaomi Redmi Note 10 on Android 13 on Aurora Nextnet 0.27.1-libwallet-v1.4.1-rc.0 b306

**Screenshot:**
![photo_2024-10-03 17 04 06](https://github.com/user-attachments/assets/57a9246f-2a9d-41be-9183-b65a3c16c1b9)

**Comment by igordanilcenko** [comment]
This isn't a bug. The only things that are restored from seed words are txs and balance. So contacts, unfortunately, won't be restored as expected
