### ISSUE TITLE
[TTL] Balance is not refreshed properly

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-android#1238]
**Describe the bug**
When I restore my wallet on AAurora, using the seed phrase from my tari universe app, I find that my wallet balance on Aurora is incorrect. It should be the same as on my tari universe app which 9s 6.987 tXTM

**To Reproduce**
1. User should have tXTM on tari universe
2. Download Aurora Android app
3. Open app
4. Select option to restore an existing wallet
5. Select to restore via recovery phrase
6. Add recovery phrase from tari universe app
7. Select ok
8. Once app is recovered view balance and transaction history

**Expected behavior**
When I restore my wallet on Aurora I should see the balance from my wallet

**Screenshots**
![photo_2024-10-11 12 33 14](https://github.com/user-attachments/assets/ff63332f-74bb-4130-a0c3-241fa2564a48)
![Screenshot (71)](https://github.com/user-attachments/assets/6c084e5c-0783-4ba7-918b-e9c8b7636d21)

**Desktop (please complete the following information):**
  - Aspire A315-59
  - Windows 11, version 23H2

**Smartphone (please complete the following information):**
 - Device: Galaxy A33 5G
 - OS: One UI Version: 6.1
 - Android version 14
 - Browser & Version [e.g. stock browser v0.1.2]

**Tari Aurora App version:**
NextNet 0.27.1-libwallet-v1.4.1-rc.0b306

**Comment**
0.5.18: Aurora: When miner app wallet is restored on Aurora via seed phrase, I find that my wallet balance on Aurora is at 0

**Comment by Anziskavds** [comment]
Tested successfully on Xiaomi Redmi Note 10 on Nextnet 0.28.1-libwallet-v1.8.0-rc.0 b315.
