### ISSUE TITLE
There is no option for a user to connect their Yat on Android

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/wallet-android#1242]
**Description:**
There is no option for the user to connect their Yat to their Aurora wallet on Android.

**Steps to reproduce:**
1. User should go to their profile screen
2. User should see a Connect Yat button
3. There is no Connect Yat button on their profile screen or in settings

**Expected behaviour**
User should have a Connect Yats button on their Profile screen

**Screenshot:**
![photo_2024-10-22 18 06 36](https://github.com/user-attachments/assets/1ba4bc91-8b46-49e3-991e-b9167fc4dee4)

**Device:**
Xioami Redmi Note 10 on Android 13

**Aurora version:**
Esmerelda 0.28.1-libwallet-v1.7.0-pre.3 b313

**Comment by igordanilcenko** [comment]
It's hidden on purpose for now. The option will be available once the Yat feature is fully fixed

**Comment by igordanilcenko** [comment]
Duplicates #1118 . Will be fixed once it's fixed
