### ISSUE TITLE
Encrypt private key before storing in shared preferences.

### ISSUE THREAD

**Issue by kukabi** [tari-project/wallet-android#125]
Currently the private key hex string is stored in shared preferences non-encrypted.

**Comment by Jasonvdb** [comment]
@kukabi how would you decrypt it from a background process? I haven't figured this out for iOS yet...

**Comment by kukabi** [comment]
@Jasonvdb I'm not sure if Android disables using the keystore from background, haven't looked into it yet but found some libraries([1](https://github.com/adorsys/secure-storage-android), [2](https://github.com/yakivmospan/scytale)) and their pages do not mention about such an issue. Will update here once I give them a try.
