### ISSUE TITLE
Txs on Home Page are not refreshed correctly

### ISSUE THREAD

**Issue by igordanilcenko** [tari-project/wallet-android#1257]
Sometimes the tx list on the Home Page contains outdated items (with the wrong status or with incomplete data). The list of txs on the Tx List screen is always up-to-date and contains different items.
We should fix tx list refreshing.

**Comment by Anziskavds** [comment]
Tested successfully on Xiaomi Redmi Note 10 on Nextnet 0.28.1-libwallet-v1.8.0-rc.0 b315.
