### ISSUE TITLE
[Feature] Updated Emoji ID UI/UX

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-android#153]
@talmahaj commented on [Fri Mar 13 2020](https://github.com/tari-project/wallet-ios/issues/174)

See [parent](https://github.com/tari-project/tari/issues/1476)

**Comment by Tas4tari** [comment]
Tested successfully as per designs and video on Huawei P30 lite

**Comment by Tas4tari** [comment]
Tested successfully on Android, device Huawei P30 lite
v0.1.10-jnlLibs-0.9.1
![Screenshot_20200505_111608_com tari android wallet](https://user-images.githubusercontent.com/50987039/81051433-f5175200-8ec1-11ea-90dd-8ed952e5fbca.jpg)
