### ISSUE TITLE
Testnet Tari request doesn't get a retry after turning on network connection.

### ISSUE THREAD

**Issue by kukabi** [tari-project/wallet-android#169]
Currently a retry will only be made at a restart, the app should listen to the network status & retry accordingly.

**Comment by Tas4tari** [comment]
When install app and go to home screen and receive Tari.
To test go through onboarding on the home screen with the internet off. Turn on internet connection and confirm you receive tari

**Comment by Tas4tari** [comment]
Tested successfully, waited 2 minutes before turning the internet back on, as soon as connection was re-established on my device I received Tari from the TariBot
