### ISSUE TITLE
[Feature] Publish custom deep link scheme and respond accordingly.

### ISSUE THREAD

**Issue by kukabi** [tari-project/wallet-android#171]
At the moment custom URL scheme is not exported & no incoming deep link is processed.

**Comment by jigneshsanghani** [comment]
Works fine for me!

**Comment by Tas4tari** [comment]
@kukabi @jigneshsanghani  As per @CjS77 this is still an issue

**Comment by talmahaj** [comment]
@kukabi I'm not sure I remember what this one is? We did want to implement universal links at some point, should we maybe convert this ticket into that?

**Comment by kukabi** [comment]
@talmahaj We actually have implemented deep links. I think @CjS77 wasn't able to navigate a deep link into the app, but I wasn't able to reproduce the issue. @Tas4tari can we please test if the deep links are working?

**Comment by Tas4tari** [comment]
@kukabi We tested the deep-link with default amount and notes and that worked as per how @nyarian showed me how to test it , will close of this ticket
