### ISSUE TITLE
IBM ICU library takes up too much space.

### ISSUE THREAD

**Issue by kukabi** [tari-project/wallet-android#172]
`icu4j`, which we use to process emojis, takes up around 22MB in the distributable bundle. Let's find out if it takes up this much space on the actual device, and if so, let's try to find a way of minimizing it, or to use a smaller library or get rid of this library altogether.
![Screen Shot 2020-03-19 at 14 42 04](https://user-images.githubusercontent.com/2969501/77064272-3f1aa600-69f0-11ea-8bae-1549ffd773ad.png)

**Comment by Tas4tari** [comment]
@kukabi Unable to test as this is a technical issue, have chatted to @nyarian and decided to close as such
