### ISSUE TITLE
Wallet instantiation time.

### ISSUE THREAD

**Issue by kukabi** [tari-project/wallet-android#173]
Wallet instantiation takes too long in some cases, and this blocks the UI since the wallet is injected by Dagger in `onCreate` for activities, and `onCreateView` for fragments. You can see a small blocking of the TARI Wallet animation right after the introduction screen. Let's find a way to eliminate this issue & make the instantiation async.

**Comment by Tas4tari** [comment]
To test:
Kill the app completely then reOpen the app for the second time and ensure if it takes long ensure there's a progress bar displayed

**Comment by Tas4tari** [comment]
Tested successfully, I killed the app completely (did a force stop in settings), when i restarted app was launched and loaded very quickly, therefore there was no progress bar displayed. Tested on Huawei P30 lite

**Comment by Anziskavds** [comment]
I tested from a Samsung S9 and an iPhone 7 and both devices tested successfully. After the app was completely closed, the app reloaded very quickly.
