### ISSUE TITLE
Wallet profile button does not work

### ISSUE THREAD

**Issue by CjS77** [tari-project/wallet-android#181]
Device: Huawei Mate P20
Android version: ??
App Version: 14 - jniLibs 0.3.0

## Steps to reproduce
1. From main screen, tap "My profile" icon
Nothing happens.

This works on the Pixel 3.

**Comment by SWvheerden** [comment]
This also does not work on Pocophone F1
Android version: 10 QKQ1.190828.002
MIUI version: 11.0.4.0 (QEJEMIXM)
App version: 0.0.13-jniLibs-0.2.3
