### ISSUE TITLE
Missing funds on startup

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/wallet-android#193]
Version: 0.0.16
Android version: 10
Phone: Pocophone F1

Issue:
When I started up the app, the funds displayed in the up is less than the funds the tari bot sent me. 
![image-0b7acfed-ee0a-4363-a8e7-e06bef9c66c4](https://user-images.githubusercontent.com/2579813/77403397-e0bb4200-6db8-11ea-8f95-cdf3a50cf4d6.jpg)

**Comment by kukabi** [comment]
@SWvheerden does the problem persists after the latest updates?

**Comment by Tas4tari** [comment]
As per @SWvheerden this was not reproducible with the new builds. Therefore closing
