### ISSUE TITLE
App backup.

### ISSUE THREAD

**Issue by kukabi** [tari-project/wallet-android#194]
After an uninstall->reinstall, data from the previous wallet persists if backup is enabled in the manifest file. Let's think if this behavior is preferred.

**Comment by CjS77** [comment]
This is arguably desired behaviour; it;s just annoying for testnet

**Comment by kukabi** [comment]
I'm reopening it as a question. @CjS77

**Comment by Tas4tari** [comment]
@kukabi With the new Back up and Restore feature can this be closed or is the discussion still ongoing?

**Comment by kukabi** [comment]
@Tas4tari I'm not sure. Android has support for local backup without doing anything extra, the question is whether we'd like to use that feature or rely on our solution only.

**Comment by kukabi** [comment]
@Tas4tari On a second thought, it looks like it's safe to close this issue now. We have the explicit way to backup and restore, it should be enough for the moment. Closing.
