### ISSUE TITLE
Optimize FFI calls.

### ISSUE THREAD

**Issue by kukabi** [tari-project/wallet-android#221]
Possibly reduntant FFI calls need to be eliminated.

**Comment by Tas4tari** [comment]
@kukabi How do i test this?

**Comment by kukabi** [comment]
I don't think it's testable from a user's perspective @Tas4tari. I think it can be tested through code review. I'm not sure.

**Comment by Tas4tari** [comment]
@Tas4tari Chat to Phil about this.

**Comment by Tas4tari** [comment]
As per @philipr-za :	
It is better but I am still seeing some redundant calls but I don't think its a big deal. Lets close this for now and revisit later if need be
