### ISSUE TITLE
Backend Mobile: Wallet: Transaction history

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-android#23]
Store all data related to transactions I've sent and received.

Expose an API that has

- get_tx_list (filters) - list all my transactions, or filter by sent/received/to dest_pubkey/from src_pubkey

The status on tx's should be kept current by communicating with a base node (confirmed = >NNN confirmations, pending = <NNN confirmations, unconfirmed = in mempool, else unknown).

Rejected txs won't be identifiable on the blockchain, so these would have to be tracked and marked locally.

**Comment by talmahaj** [comment]
@CjS77 @Tas4tari  can we close this since we have that other ticket already for the transaction history list?

**Comment by CjS77** [comment]
Sure
