### ISSUE TITLE
QA:Tari Spinning Logo: Freeze for a few seconds

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-android#230]
Steps to reproduce:
1. Open tari app for first time
2. Hit create wallet button
3. Tari logo comes down and animates into spinning I thing
4. there was a small stutter as the Tari logo came down to the middle of the screen
5. the spinning I seemed to freeze before finishing, as the I got stuck in a bit of a diagonal position for a couple of seconds (like at the angle of a backslash) before the white view slide up

Device: Samsung Galaxy A10
O.S: 9.0

**Comment by kukabi** [comment]
@Tas4tari @talmahaj #225 makes sure the animation gets completed, but you might experience a short wait between when the logo animation completes and the onboarding screen shows up. This is addressed by #173, so I think it's safe to close this issue when #225 gets merged in.
