### ISSUE TITLE
QA: Enter amount: Occasionally digits do not register when entering an amount

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-android#231]
**Description:**
When I enter the amount of tari on the keypad, sometimes it doesn’t seem to register one of the digits. It seems to happen when I enter them too fast, but that speed is also the normal speed at which I usually enter numbers on these types of interfaces. 
Device: Samsung Galaxy A10
O.S: 9.0
Question:
Can we support speedier keypad entry?

**Comment by talmahaj** [comment]
@kukabi I am still having this issue despite being on 0.0.21, any ideas?

**Comment by kukabi** [comment]
@talmahaj it should be more responsive now (I halved the response time), but I can still make it faster, let's see if it gets better with the next version.

**Comment by Tas4tari** [comment]
Tested via Android on Huawei P30 lite, all digits register. Tested on version: 0.1.4-jniLibs-0.7.1.
@talmahaj Do we have a company broswerstack account that can be used as the free trial version does have limited devices therefore unable to test on the device mentioned in the description
