### ISSUE TITLE
QA: Transactions: 2 Transactions displayed as - 5000 despite user not sending any Tari

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-android#234]
**Description:**
I was able to get through to the transaction screen. I did notice on this device I got 2 transactions for ~5,000 Tari even though I did not get to the point of sending the Taribot any Tari. Maybe that airdrop is something new you guys are working on

**Device Details:**
Samsung SM-J260M
Android 8.1.0

**Comment by kukabi** [comment]
@Tas4tari I think this issue is invalidated by the latest UTXO import updates. I'm not very clear about the issue either, can we please check whether it persists? I'm closing it for the moment.
