### ISSUE TITLE
QA: App Crash on Transactions and passcode authentication

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-android#235]
**Description:**
The app crashed shortly after I got to the transaction screen and now it crashes immediately after passcode authentication. 

**Device Details:**
Samsung SM-J260M
Android 8.1.0

**Comment by kukabi** [comment]
@Tas4tari Can we ask if this persists after the latest updates?

**Comment by Tas4tari** [comment]
@Tas4tari  To follow up

**Comment by Tas4tari** [comment]
@kukabi  @talmahaj  As received from Robin:
Hey @tas regarding the Android crashing, here is a video of the app on the Samsung 32-bit device using the 4/1/20 build

You'll see the crashing I reported earlier was probably due to the lack of a passcode, as I am seeing here that the app runs fine with a passcode, but crashes frequently without a passcode.

@egads implied we may already be working on this, but here are the videos regardless.

PASSCODE ON DEVICE
https://www.dropbox.com/s/413vwg229dn5rgg/Android-code.mov?dl=0

NO PASSCODE ON DEVICE
https://www.dropbox.com/s/yb6vcez220sn6fp/Android-nocode.mov?dl=0

**Comment by Tas4tari** [comment]
@talmahaj @kukabi Please see feedback as received:
Sorry for delay. Here is a video. It’s actually working worse now. Before I could setup a wallet with pin Authentication on. Now I can’t do it with or without 

https://www.dropbox.com/s/7k35htwxxx5ilxz/Video%20Apr%2007%2C%201%2049%2008%20PM.mov?dl=0

**Comment by Jasonvdb** [comment]
Another user reported this happening on a Samsung Galaxy grand prime pro (J2)

![IMAGE 2020-06-29 14:26:28](https://user-images.githubusercontent.com/5300488/86005139-857e9880-ba14-11ea-8d0b-d382a68297fe.jpg)
![IMAGE 2020-06-29 14:26:38](https://user-images.githubusercontent.com/5300488/86005154-8c0d1000-ba14-11ea-898d-44744f9de058.jpg)

**Comment by Tas4tari** [comment]
@Tas4tari to follow up with Robin

**Comment by Tas4tari** [comment]
@kukabi Please see comment from Robin:
_Hi Natasha, Aurora doesnt get past the splash screen on my android device. It never really has, I'm not sure what is wrong with this device, it's pretty poor with all apps. I think it might just be too old in general._
Would the logs still help?

**Comment by talmahaj** [comment]
Did that “not responding” error happen after they hit Proceed?

**Comment by Tas4tari** [comment]
Did a follow up, waiting for feedback

**Comment by Tas4tari** [comment]
Confirmed with Robin, this was not related to the authentication error above in any way
cc @talmahaj @kukabi

**Comment by Tas4tari** [comment]
Just had Robin retest the latest version of the app on the device and he has relayed the new version is working really well on the Samsung SM-J260M, therefore closing this issue

cc @talmahaj @kukabi
