### ISSUE TITLE
QA: Tari Wallet icon is not the same as other icons

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-android#237]
**Description:**
I've noticed the icon is not the same as other icons. Is this a designer thing or maybe how the icon is set in the Google Store admin?
**Device Details:**
Samsung SM-J260M
Android 8.1.0

![IMG_3271](https://user-images.githubusercontent.com/50987039/77758142-1ff8c580-703b-11ea-8a22-caa75a3c05c8.jpg)

**Comment by kukabi** [comment]
Addressed by #228 too.
