### ISSUE TITLE
[Enhancement] Remove "Hello Friend" step in wallet onboarding

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-android#240]
@talmahaj commented on [Sun Mar 29 2020](https://github.com/tari-project/tari/issues/1621)

We've been getting feedback that the onboarding process drags out a bit, and we don't disagree, so we'd like to remove the "Hello Friend" step from the mobile wallet onboarding process.

**Acceptance Criteria**
- "Hello Friend" step no longer appears in onboarding

**Comment by kukabi** [comment]
@talmahaj I understand we start from the "We're off to a great start" step, is it correct?

**Comment by talmahaj** [comment]
Nope, we’re still keeping the “Hold on a sec” part of the animation.

**Comment by talmahaj** [comment]
Pls let jay know too, I’m in bed and need to sleep 😴😴😴

**Comment by kukabi** [comment]
Alright. @Jasonvdb
