### ISSUE TITLE
Emoji ID behavior tweaks

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-android#243]
- Naveen request: "on this "this is your Emoji ID" screen in onboarding, it should first show your full Emoji ID, and then shrink down to showing the short form version with the button there"

- On that same screen, you should be able to tap the emoji ID again for it to collapse (and again for it to expand again, and so forth and so forth)

**Comment by talmahaj** [comment]
@kukabi 
This looks great so far! One outstanding piece of functionality that doesn't look like it's been implemented yet: it should first show your full (expanded) Emoji ID for a second, and only then shrink down to showing the short form version with the button there

**Comment by kukabi** [comment]
@talmahaj ok I'll include this update with the next release.

**Comment by Tas4tari** [comment]
Tested on device: Huawei P30 lite, version: 0.1.4-jniLibs-0.7.1.
User first sees the full emoji ID created, it then shrinks down and displays the "Tap to see full Emoji ID" button, when user selects this button the Emoji ID is expanded and the button is no longer visible, when they tap on the Emoji ID again it thereafter shrinks down and the "Tap to see full Emoji ID" button is displayed again.
Closing as it seems to be working as per the description and as per @talmahaj last comment
cc @talmahaj
