### ISSUE TITLE
QR code scanning issues

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-android#244]
From Lee:
- Hang on Android app trying to scan QR code, three times in a row
- Samsung A71 
- this is with version 0.0.18

From Phil:
- I have also nocticed on my phone that opening QR code the camera app starts and hangs for a long time. Eventually it sorts itself out but after about a minute

More chatter about this:

	
simian
5:29 AM
ok will leave to you to make the issue, on my Xaiomi Mi 9 the camera apps half starts (shows the view finder overlay) but the camera doesn't seem to start so just black screen and app becomes un responsive
kutsal profile image	
kutsal
5:30 AM
and @leet when does it freeze? the moment you tap the button or later?
leet profile image	
leet
5:30 AM
as @simian says, the camera display comes up, get a few scans/overlay ... about to start focus and then it hangs ...
took about 5min before it came back, thou my phone did go into screensaver mode ...
once unlocked, it was waiting for QR scan
kutsal profile image	
kutsal
5:31 AM
do you get asked for the camera permission?
leet profile image	
leet
5:31 AM
my camera does have an unfocus image thou ...
app already had perms
kutsal profile image	
kutsal
5:32 AM
ok so I guess you gave the permission earlier?
and the freeze happened after the permission the first time?
leet profile image	
leet
5:32 AM
also, I seem to be short of funds ... the two 5K tari, then a few 200 out and today I am at 4.7K tari ...
I had opened the QR scanner before, when I had given the app camera perms
kutsal profile image	
kutsal
5:33 AM
alright will have a look thanks!

**Comment by Tas4tari** [comment]
As per @kukabi This is device specific, solution in mind that @kukabi  will implement on Monday

**Comment by kukabi** [comment]
Also from @simian : My camera still struggles to open on my Xaomi Mi 9

**Comment by alexandrVakhtinTari** [comment]
I've got Xaomi Redmi 9 Pro and it's working fine, also no complaints from the team
