### ISSUE TITLE
Error message when discovery fails

### ISSUE THREAD

**Issue by Jasonvdb** [tari-project/wallet-android#248]
If a discovery fails we need to show a user this error message as it's most likely failing because the recipient is offline:

Heading: `Sorry, you can't send Tari to offline users`
Body: `Please make sure your recipient has a reliable internet connection and has the Aurora app open on their device, and then try again. If that doesn't work, please verify you have the correct Emoji ID.`

iOS: https://share.getcloudapp.com/JruWBe2x

**Comment by talmahaj** [comment]
No longer relevant
