### ISSUE TITLE
QA: Transaction sent: When a transaction is processed, it does not show up as Pending

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-android#249]
**Description:**
When transaction is sent, it does not show up as pending BUT balance is decremented

**Comment by kukabi** [comment]
I'm hoping the callback observation and feedback messages introduced by #256 will fix this flow.

**Comment by kukabi** [comment]
Rest of the issue is not here - but I'm guessing that the balance probably got restored after a while.

**Comment by talmahaj** [comment]
@Tas4tari pls confirm fixed with reporter, thx!

**Comment by Tas4tari** [comment]
Requested feedback from Leland

**Comment by Tas4tari** [comment]
Tested on Huawei P30 lite, version: 0.1.4-jniLibs-0.7.1. and was unable to reproduce. Will confirm with Leland once more and if no feedback received will close accordingly

**Comment by Tas4tari** [comment]
Received feedback from Leland and it's working as expected
