### ISSUE TITLE
QA:  Send Tari: No transaction displayed and available balance rolled back

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-android#250]
**Description:**
Attempted to send 100 to Natasha, saw no transaction and available balance rolled back

**Comment by kukabi** [comment]
I think this one is similar to #249, and #256 probably will fix the flow. Let's see if it happens again after the release.

**Comment by talmahaj** [comment]
@Tas4tari pls confirm with bug reporter!

**Comment by Tas4tari** [comment]
As per Keith, this is fixed
