### ISSUE TITLE
Local Authentication copy change

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-android#252]
To make it more explicit, let's please slightly tweak the authentication copy on the external screen that the user is sent to on which they authenticate (not the one with the graphics).

**New Wallets:** 
Page Heading: "Secure your wallet"
"Please enter your smartphone's screen lock PIN, passcode, or pattern. Tari Aurora will require it each time you open the app."

**Existing Wallets:**
Page Heading: "Unlock your wallet"
"Please enter your smartphone's screen lock PIN, passcode, or pattern to unlock your wallet."

Replace "PIN, passcode, or pattern" with the word "biometrics" when relevant, thanks! On this screen we don't need to say "device lock code" anymore.

**Comment by kukabi** [comment]
@talmahaj the lock code screen is different for onboarding and regular use: we have [this screen](https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5e254635bb745e28847ad1b2) for onboarding and the one with black background and Tari logo for regular. Do we use the same screen for both cases from now own?

Also, we call the all "device lock code" now, shall we change? And we need a separate copy for biometrics.

**Comment by talmahaj** [comment]
@kukabi updated the ticket. Do you have everything you need now? Thx!

**Comment by talmahaj** [comment]
Looks great!
