### ISSUE TITLE
Change "Pending" to "In Progress"

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-android#253]
From Mattermost:

What would you think if we used "In Progress" instead of "Pending" for the status of transaction that's been sent but not yet mined? I know "Pending" is common in banking for transactions that haven't posted yet, which is why we originally went with it, but IMO "in progress" is far more explicit to the user as to what the heck that in-between state actually means (and "Pending" in banking has an association with long 1-3 day timeframes, which could be misleading)

Acceptance Criteria:
- "Pending" status in Transactions list now reads "In Progress"
- On Transaction detail screen for any transaction with In Progress state, should read "Payment In Progress" instead of "Pending Payment Sent"

**Comment by kukabi** [comment]
@talmahaj is the tx details page title the same ("Payment In Progress") for both incoming and outgoing transactions?

**Comment by talmahaj** [comment]
Yep! As we discussed on standup today.

**Comment by talmahaj** [comment]
Sadly I can't test this yet because my transactions including to Tari Bot are all failing :(

**Comment by talmahaj** [comment]
@kukabi on list screen, pls display "In Progress" as the section title without the word "Transactions"

**Comment by talmahaj** [comment]
Seeing this ticket under In Progress is very meta, btw :P

**Comment by Tas4tari** [comment]
Tested on device Huawei P30 lite, version: 0.1.4-jniLibs-0.7.1.
Transactions list displays as "In Progress" and Transaction detail screen displays as: "Payment In Progress"
Screenshots attached below:
![Screenshot_20200420_140119_com tari android wallet](https://user-images.githubusercontent.com/50987039/79749738-01bb7800-8310-11ea-9bb9-07a632864858.jpg)
![Screenshot_20200420_140125_com tari android wallet](https://user-images.githubusercontent.com/50987039/79749761-0c760d00-8310-11ea-9ea3-d24743d1a2ce.jpg)
