### ISSUE TITLE
Delay store modal by 2 additional seconds

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-android#255]
Pretty self-explanatory ticket. Let's give the user another 2 seconds to see the second faucet transaction come in before popping the store modal. Or 1.5 seconds if 2 feels like a drag once you implement it...

**Comment by talmahaj** [comment]
Can't test due to failing transaction issues :(

**Comment by Tas4tari** [comment]
After the first successful send, the  transaction list for 2 seconds, TTL store modal should pop up after another 2 second delay

**Comment by Tas4tari** [comment]
Tested successfully on Huawei P30 lite
