### ISSUE TITLE
Browserstack Glaxy J7 Prime UI Issues

### ISSUE THREAD

**Issue by kukabi** [tari-project/wallet-android#260]
Transaction fee text looks but off in add amount screen:
![Screen Shot 2020-04-03 at 22 03 54](https://user-images.githubusercontent.com/2969501/78396475-21585e00-75f8-11ea-9a1c-2b01d7565bc9.png)

"Sending xx Tari" text doesn't show in the final screen of the send Tari flow:
![Screen Shot 2020-04-03 at 22 06 15](https://user-images.githubusercontent.com/2969501/78396611-54025680-75f8-11ea-95dc-033605e0c1a1.png)

**Comment by Tas4tari** [comment]
Tested successfully via browser-stack, screenshots attached:
<img width="441" alt="Screen Shot 2020-05-04 at 3 44 56 PM" src="https://user-images.githubusercontent.com/50987039/80972373-52f25e00-8e1e-11ea-8ef2-9e5fc7e4585e.png">
<img width="466" alt="Screen Shot 2020-05-04 at 3 44 44 PM" src="https://user-images.githubusercontent.com/50987039/80972390-58e83f00-8e1e-11ea-88c9-74a828c87e43.png">
<img width="459" alt="Screen Shot 2020-05-04 at 3 44 32 PM" src="https://user-images.githubusercontent.com/50987039/80972393-5ab20280-8e1e-11ea-87c2-6e4b9cbc5a75.png">

**Comment by Tas4tari** [comment]
<img width="424" alt="Screen Shot 2020-05-04 at 3 43 56 PM" src="https://user-images.githubusercontent.com/50987039/80972457-6bfb0f00-8e1e-11ea-926b-c9f79dc0211c.png">
