### ISSUE TITLE
Terminate discovery process and fail transaction if not successful within 20 seconds

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-android#261]
@talmahaj commented on [Sun Apr 05 2020](https://github.com/tari-project/wallet-ios/issues/246)

See [parent](https://github.com/tari-project/tari/issues/1672)

**Comment by Tas4tari** [comment]
@talmahaj As this is an older issue and the discovery was tested here can: https://github.com/tari-project/wallet-android/issues/277 Can I close this
