### ISSUE TITLE
Create multiple testing groups with diff builds assigned to each

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-android#262]
@talmahaj commented on [Mon Apr 06 2020](https://github.com/tari-project/wallet-ios/issues/248)

@talmahaj commented on [Mon Apr 06 2020](https://github.com/tari-project/tari/issues/1673)

Naveen (rightly) mentioned we need to be starting to maintain test builds for new features that are separate from the "production" builds we're sharing with investors, just in case there's something major broken or a regression in the testing build. So we'd distribute the builds for QA/UAT internally (even if just to a smaller group) before merging with the beta build.

So maybe we want a "Production" group of which everyone has access to the builds, and then a "Test" group for new features to be added before we decide they're ready to merge to the Prod builds. And then more granularly, maybe single feature builds can be assigned just to an even smaller group (e.g. us, karim, natasha) for QAT and UAT even before folks like naveen in the Test group see them

**Comment by kukabi** [comment]
@Tas4Tari @talmahaj We already support this through Play Store internal test, alpha, beta and production releases. Can this issue be closed?

**Comment by Tas4tari** [comment]
@kukabi I've noticed when I have the Beta build installed on my device, I can't download the Production build because when I search the store it only gives me the option for the Beta build. Is this because I am apart of the test group?
