### ISSUE TITLE
[Feature] Edge case handling: error messages

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-android#263]
@talmahaj commented on [Mon Apr 06 2020](https://github.com/tari-project/wallet-ios/issues/249)

@talmahaj commented on [Tue Jan 21 2020](https://github.com/tari-project/tari/issues/1227)

**User Story**

> When I can't use the app, I want an informative, persistent notification telling me why and what to do next

---

**Acceptance Criteria**

1. If the edge cases in either [row 2, 4, or 5 here](https://docs.google.com/spreadsheets/d/1E5gNJXIl14mE0zeJBTZt5OPj0SHKkQEGXYHeLkXpAXY/edit#gid=0) are true, display persistent modal with [the following copy](https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5e26abe8de3d8994256095e8) except instead of "it's not you, it's us," the heading should be "It's not you, it's the network"
2. If the user has inadequate or no connectivity per [row 15 here](https://docs.google.com/spreadsheets/d/1E5gNJXIl14mE0zeJBTZt5OPj0SHKkQEGXYHeLkXpAXY/edit#gid=0) AND either taps the send button or attempts to progress to the next step in a transaction, display a modal with the following copy (that the user can tap outside of to close):
"Can’t connect to the internet"
"Your phone appears to be offline or has a poor connection at the moment. Please try again when you’ve found a stronger signal."

---

**Design**

Design specs: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/dashboard?seid=5e26ac2d8a5b6752fe7a0377

-----

**Implementation Notes**

- More details on the wallet edge cases can be found here: https://docs.google.com/spreadsheets/d/1E5gNJXIl14mE0zeJBTZt5OPj0SHKkQEGXYHeLkXpAXY/edit#gid=0

**Comment by talmahaj** [comment]
@kukabi Updated the acceptance criteria to cover what we discussed on our call the other day

**Comment by Tas4tari** [comment]
Tested on device: Huawei P30 lite, version: 0.1.4-jniLibs-0.7.1.
Edge case: 2, 4, 5 - Still needs to be tested
Edge case 15: User receives the interwebs error as per the design and the copy here: https://docs.google.com/spreadsheets/d/1E5gNJXIl14mE0zeJBTZt5OPj0SHKkQEGXYHeLkXpAXY/edit#gid=0  Screenshots attached below:
![Screenshot_20200420_141400_com tari android wallet](https://user-images.githubusercontent.com/50987039/79750944-0ed96680-8312-11ea-8bbd-21f927f2f935.jpg)
![Screenshot_20200420_141248_com tari android wallet](https://user-images.githubusercontent.com/50987039/79751032-33cdd980-8312-11ea-9eda-ab120061e9b5.jpg)

**Comment by Tas4tari** [comment]
Received an edge case:  Wording is slightly different than what is on the spreadsheet, @talmahaj Can you confirm if the wording on the below screenshot is acceptable:
![Screenshot_20200421_112852_com tari android wallet](https://user-images.githubusercontent.com/50987039/79867998-8f19cd80-83df-11ea-9891-7ea882f24471.jpg)

**Comment by Tas4tari** [comment]
@kukabi Confirmed with the following doc, that it should say "Can you give us a few min" https://docs.google.com/document/d/1nn8rA388Lm9aU8ft7keSlDse8at0D-3w9MCapD-de2s/edit#heading=h.a7r6aqwtn0ra

**Comment by Tas4tari** [comment]
@kukabi Error message still states: "Can you give us a bit" so has not changed

**Comment by kukabi** [comment]
Sorry @Tas4tari, looking.

**Comment by Tas4tari** [comment]
Tested successfully on Android, device Huawei P30 lite
v0.1.10-jnlLibs-0.9.1
![Screenshot_20200505_123628_com tari android wallet](https://user-images.githubusercontent.com/50987039/81057703-3bbe7980-8ecd-11ea-9839-67320c0960e4.jpg)
