### ISSUE TITLE
Connectivity issue error modal copy change

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-android#265]
"It's not you, it's us" ---> "It's not you, it's the network"

Thanks for the feedback @Jasonvdb !

**Comment by Tas4tari** [comment]
Tested successfully, copy changed as expected

![Screenshot_20200421_112852_com tari android wallet](https://user-images.githubusercontent.com/50987039/79867375-8c6aa880-83de-11ea-913d-6306655f115b.jpg)
