### ISSUE TITLE
QA Notes

### ISSUE THREAD

**Issue by kukabi** [tari-project/wallet-android#267]
Karim's QA notes:
https://www.dropbox.com/s/l1vgdqvjoa0wb9y/QA-Android.mp4?dl=0

**Acceptance Criteria**

Splash Screen
- Make logo 5% larger on splash screen
- Button missing pressed state/animation that is seen on other buttons in the app

White bg sliding over black bg animation
- Add easing similar to the easing seen when the Tari Aurora logo moves from the top to the middle of the page

Create your Emoji ID
- remove drop shadow

Let's secure your wallet
- "Let's secure your wallet" animation is missing the easing seen in "This is your Emoji ID" when the text starts appearing

Welcome to your wallet
- As this view appears from the bottom, add the same easing as is mentioned for the black/white bg animation

"You got some testnet Tari"
- Can we get all our modals to slide in from the bottom the way action sheets do in iOS, maybe with a bit of easing added? What is the LOE? This wasn't in the original specs but would be great if not more than 1-2hrs or so of effort

Amount/Notes screen
- Back arrow and recipient are too high up, should be same height as in transaction detail screen

Profile
- Emoji ID does not collapse and expand as it does on other screens

@karim-tari to-dos
- Wallet creation loader is 2x the size it is supposed to be
- Karim says TARI does not properly slide into the I in initial animation, he'll take a look at the file

**Comment by Tas4tari** [comment]
Tested on my Huawei P30 lite, Karim do you want to perhaps have a quick look at this before I close?

**Comment by Karim-tari** [comment]
Thanks, will do. Is this available for me to test on BrowserStack?

**Comment by Tas4tari** [comment]
@Karim-tari  Hi yes this is available

**Comment by talmahaj** [comment]
I'll let @Karim-tari advise on the easing, but otherwise these changes all look great to me! Nice work @nyarian

**Comment by Karim-tari** [comment]
Agreed, I think it looks great. Easing looks great as well.

**Comment by Tas4tari** [comment]
@Karim-tari Thank you, closing this out
