### ISSUE TITLE
Tor Executable Client Transport Plugin Configuration

### ISSUE THREAD

**Issue by kukabi** [tari-project/wallet-android#273]
These params need to be added to the Tor proxy shell command to enable bridges & evade internet censorship:

```"--ClientTransportPlugin", "obfs4 socks5 127.0.0.1:47351"```
```"--ClientTransportPlugin", "meek_lite socks5 127.0.0.1:47352"```

**Comment by alexandrVakhtinTari** [comment]
Added it when was implementing Tor Bridges
