### ISSUE TITLE
Update "transaction in progress" animation that appears once sender initiates transaction

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-android#277]
@talmahaj commented on [Wed Apr 15 2020](https://github.com/tari-project/wallet-ios/issues/272)

See [parent](https://github.com/tari-project/tari/issues/1707)

**Comment by Tas4tari** [comment]
Tested successfully on Huawei P30 lite, Aurora version: v0.1.5-jniLibs-0.7.2
![Screenshot_20200421_140354_com tari android wallet](https://user-images.githubusercontent.com/50987039/79864231-6abaf280-83d9-11ea-9e00-6bc813c66aab.jpg)
