### ISSUE TITLE
Change legal links on app splash screen

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-android#286]
@talmahaj commented on [Mon Apr 20 2020](https://github.com/tari-project/wallet-ios/issues/288)

Change the URLs on the app splash screen to the following:

https://www.tari.com/privacy_policy/
https://www.tari.com/user_agreement/

**Comment by Tas4tari** [comment]
Tested successfully on Huawei P30 lite, App version: v0.1.8-jnLibs-0.9.0
