### ISSUE TITLE
Ability to remove sender name

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-android#287]
The user may want to remove the name of a contact after adding it so that their emoji ID appears again instead. Currently the app does not allow you to do this.

Acceptance Criteria: When you erase the contact name and hit the return key, the user's emoji ID should appear again.

**Comment by Anziskavds** [comment]
Tested successfully on Android version 0.1.15 on the Prod app. When a contact is saved and I click on edit, I am able to remove the contact name, click on done, and when I click the back button the name is removed successfully. 

https://share.getcloudapp.com/wbuW7jOK
