### ISSUE TITLE
Disable swipe nav feature on Transaction Note screen

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-android#291]
@talmahaj commented on [Tue Apr 21 2020](https://github.com/tari-project/wallet-ios/issues/300)

User feedback: "gonna put this out there... i love the swipe and think it's dope... but the last three times I tried to swipe the button, I swiped back to the previous page by accident and had to re-type my message   
my fellow sausage fingers out there are going to struggle"

Jay's response: "yeah I've done this, thinking I need to disable that swipe nav feature on this view only"

So yeah, pls disable swiping to navigate on the Add Note screen :)

**Comment by Jasonvdb** [comment]
Is there even a swipe view back gesture here on android or is that just an iOS thing?

**Comment by kukabi** [comment]
@Jasonvdb it's just an iOS thing. @tas4tari could you please confirm and close this issue?

**Comment by Tas4tari** [comment]
@kukabi @talmahaj @Jasonvdb Checked on my Android, tried to replicate the behavior and I am unable to, therefore closing
