### ISSUE TITLE
[Feature] Ability to be notified about cancelled transactions and see them in tx list #1744

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-android#294]
@talmahaj commented on [Tue Apr 21 2020](https://github.com/tari-project/tari/issues/1744)

@talmahaj commented on [Tue Apr 21 2020](https://github.com/tari-project/wallet-android/issues/293)

**Comment by Tas4tari** [comment]
Tested on Huawei P30 lite:

- When user hits Cancel Transaction button, a standard alert should appear reading:
“Are you sure?” : **Tested successfully**
“Your recipient will be notified of the cancellation.” : **Tested, however wording has been changed**
“Not now” “Yes, Cancel” : **Tested successfully**

- Cancelled and Expired transactions should appear in the transactions list for both the sender AND receiver, and both with the same style (grey pill, no + or - sign)  **Tested unsuccessfully as recipient does not see the cancelled transaction in their wallet @nyarian **

- Transaction detail page should read “Payment Cancelled”, with the “From” or “To” indicating to user which way the payment was sent. : **Tested successfully**

**Comment by Tas4tari** [comment]
**Recipients Transaction list: Take note of the 2 transactions in progress**
![Screenshot_20200525-122006_Tari Aurora](https://user-images.githubusercontent.com/50987039/82805379-3927c200-9e84-11ea-9ebf-3102e5d6e453.jpg)

**Sender's Transaction list: Take note of the 2 cancelled transactions:**
![Screenshot_20200525_123609_com tari android wallet](https://user-images.githubusercontent.com/50987039/82805585-8ad04c80-9e84-11ea-8489-b6b5639e0af9.jpg)

**Comment by Tas4tari** [comment]
**New wording:**
![Screenshot_20200525_111554_com tari android wallet](https://user-images.githubusercontent.com/50987039/82805874-0631fe00-9e85-11ea-8f25-8fbb06bff634.jpg)

**Comment by nyarian** [comment]
@Tas4tari these are updated requirements about wording: https://github.com/tari-project/tari/issues/1743 .

**Comment by Tas4tari** [comment]
@nyarian Thanks just added the screenshot for verification purposes

**Comment by Tas4tari** [comment]
@nyarian The transactions have still not registered as cancelled on the Recipients side, please see below screenshot:
![Screenshot_20200526-091018_Tari Aurora](https://user-images.githubusercontent.com/50987039/82872216-01c41e80-9f33-11ea-9ee5-1d8a95514033.jpg)

**Comment by Tas4tari** [comment]
Had a discussion with @Jasonvdb and @nyarian the recipient will have to wait for the transaction to expire after 3 days, once it has been cancelled by the sender as there is currently no way to notify the recipient of the cancellation therefore closing this ticket.
cc @talmahaj
