### ISSUE TITLE
[Feature] Ability to include default amount and note in deep link

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-android#297]
@talmahaj commented on [Tue Apr 21 2020](https://github.com/tari-project/tari/issues/1742)

**Comment by Tas4tari** [comment]
Tested on Huawei P30 lite with link provided by @nyarian : tari://rincewind/eid/🍎🕙🍔🍄🚲🤯🐸🧜🔵😱👐🛀💇📱🤑🍉😈🎁🏹🍪👂💅🎤😊🥜🐍🤐💨🔨🏄🤖🤢📻?amount=5.553634&note=hello
Used the following generator on Desktop : https://www.the-qrcode-generator.com/ and scanned using a QR Code scanner on my device.

1. Steps taken:

1. Entered the URL: tari://rincewind/eid/🍎🕙🍔🍄🚲🤯🐸🧜🔵😱👐🛀💇📱🤑🍉😈🎁🏹🍪👂💅🎤😊🥜🐍🤐💨🔨🏄🤖🤢📻?amount=5.553634&note=hello  in the code generator on desktop
2. Scanned the QR code from desktop via my device QR Code scanner
3. On my device the URL was displayed for the scanned QR code and c=various options
4. I selected to open the link and was redirected to my wallet Enter Amount screen with default amount displayed
5. I edited the amount and went to the note screen where the default note was displayed which i could edit as well

**Comment by Tas4tari** [comment]
**Desktop generator:**
<img width="1546" alt="Screen Shot 2020-05-25 at 4 03 32 PM" src="https://user-images.githubusercontent.com/50987039/82819798-4acb9280-9ea1-11ea-8d6f-49ea90e84eed.png">

**QR Code scanned on device:**
![Screenshot_20200525_155858_com application_4u qrcode barcode](https://user-images.githubusercontent.com/50987039/82819860-6b93e800-9ea1-11ea-8502-317af37f7123.jpg)

**Default amount displayed:**
![Screenshot_20200525_160026_com tari android wallet](https://user-images.githubusercontent.com/50987039/82819912-84040280-9ea1-11ea-87bb-521aed1a9c8d.jpg)

**Edited amount:**
![Screenshot_20200525_160035_com tari android wallet](https://user-images.githubusercontent.com/50987039/82819969-9b42f000-9ea1-11ea-9c45-af87316c9e1f.jpg)

**Default note:**
![Screenshot_20200525_160105_com tari android wallet](https://user-images.githubusercontent.com/50987039/82820002-a8f87580-9ea1-11ea-845b-1c1f310cccb4.jpg)

**Edited Note:**
![Screenshot_20200525_160114_com tari android wallet](https://user-images.githubusercontent.com/50987039/82820058-c6c5da80-9ea1-11ea-8164-69878e8dd62b.jpg)

**Comment by Tas4tari** [comment]
@nyarian @talmahaj @kukabi 
Just for reference I also tested when the app background process was not running (App was killed) and the deep-link took me to the wallet home-screen and not the Send Tari screen with the default amount or note

**Comment by Tas4tari** [comment]
Closing this issue as tested
