### ISSUE TITLE
Live status update in transaction details screen.

### ISSUE THREAD

**Issue by kukabi** [tari-project/wallet-android#306]
A pending in/out transaction could change state while it's being viewed on the transaction details screen, so we should listen to the state change & update.

**Comment by Tas4tari** [comment]
Tested Receive payment on Huawei P30 lite, app version v0.1.11-jnLibs-0.9.2
I find that when a payment is received, it remains on "Waiting for sender to complete transaction" and then updates directly to "Payment received", @nyarian should this not change to "final processing" I have added the screenshots of the state I see below:
**Initially opened the TDS:**
![Screenshot_20200512_115140_com tari android wallet](https://user-images.githubusercontent.com/50987039/81670938-a8df8b00-9448-11ea-9be9-b69f5b5eea5a.jpg)
**State after a few minutes:**
![Screenshot_20200512_115710_com tari android wallet](https://user-images.githubusercontent.com/50987039/81670997-bb59c480-9448-11ea-9c97-39e985af6ab2.jpg)
**State once payment is received:**
![Screenshot_20200512_120008_com tari android wallet](https://user-images.githubusercontent.com/50987039/81671038-ca407700-9448-11ea-8464-ce59b22b64a8.jpg)

**Comment by Tas4tari** [comment]
Tested Payment sent on Huawei P30 lite, app version v0.1.11-jnLibs-0.9.2
After the Sending animation process has completed, when i click on the transaction, it is at the "Completing final processing" step already which then updates to "Payment sent"
Screenshots below:
**User clicked on transaction to go to TDS:"
![Screenshot_20200512_120919_com tari android wallet](https://user-images.githubusercontent.com/50987039/81672173-1213ce00-944a-11ea-80fd-c69578059ee5.jpg)
**Payment successfully completed:**
![Screenshot_20200512_121314_com tari android wallet](https://user-images.githubusercontent.com/50987039/81672247-28218e80-944a-11ea-8b2c-741dacbdfcbd.jpg)

**Comment by Tas4tari** [comment]
Spoke to @nyarian, moving this ticket back to Up Next for investigation

**Comment by kukabi** [comment]
@Tas4tari can this issue be closed now? @nyarian

**Comment by Tas4tari** [comment]
@nyarian Will test it first before closing :) Thanks

**Comment by Tas4tari** [comment]
@nyarian  @kukabi Same issue as detailed here:
https://github.com/tari-project/wallet-android/issues/298

**Comment by Tas4tari** [comment]
**Tested on Huawei P30 lite:**

- Waiting for recipient to accept transaction: **Tested successfully**
Test proof: https://www.loom.com/share/294380435d4d46a4afcab43e1fd67648
- Waiting for sender to complete transaction: **Tested successfully**

**Comment by Tas4tari** [comment]
Waiting for sender to complete transaction live status update tested successfully:
![image-22ffd33a-c3d1-4255-9c98-0b5131b6cc7d](https://user-images.githubusercontent.com/50987039/83018588-dec66700-a025-11ea-87ca-5753accffdc9.jpg)
![image-448dfdc8-8190-4460-821b-b5282224aeb4](https://user-images.githubusercontent.com/50987039/83018651-f30a6400-a025-11ea-860c-3d4b10892c0a.jpg)
![image-9e170367-cfe5-4270-b6c5-69b6a2db25ea](https://user-images.githubusercontent.com/50987039/83018703-fdc4f900-a025-11ea-8ec0-a6f73f9ba530.jpg)
