### ISSUE TITLE
Change Tari and TestNet Tari across the app and Push Notifications to: "XTR" "tXTR" "testnet XTR"

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-android#307]
Apple don't like no mentions of the word testnet so we had to remove them. We want to be consistent across both apps, though, so let's:

- Change Tari and TestNet Tari across the app and Push Notifications to: "tXTR"
- Change "The Tari Testnet (TTL) Store" to just "The TTL Store"

---- 

Details:

@Tas4tari commented on [Fri Apr 24 2020](https://github.com/tari-project/wallet-ios/issues/312)

**List where changes are required:**

Let’s create your emoji ID screen:
Change “…send you Tari.” to “…send you tXTR”

This is your emoji ID screen:
Change “…send you Tari.” to “…send you tXTR”

Let’s secure your wallet
“Tari wallet” —> “tXTR wallet”

First faucet tx modal
“You just got some testnet Tari!” —> “You just got some tXTR!”
“…a bit of testnet Tari” —> “a bit of tXTR”
“Send Tari” button —> “Send tXTR”

Sending animation
“Sending [amount] Tari” —> “Sending [amount] tXTR”

Store modal
“Spend testnet Tari on…” —> “Spend tXTR on…”
“…testnet Tari on exclusive…” -> “…tXTR on exclusive…”

TariBot transaction message: #1
“Here’s some testnet Tari!” -> “Here’s some tXTR!”

TariBot transaction message: #2
“Here’s more Tari” —> “Here’s more tXTR”
“”Hard-earned” testnet Tari”” —> “”Hard-earned” tXTR””

Profile screen
“Share it with others to receive Tari.” —> “Share it with others to receive tXTR”
“To send you Tari” —> “to send you tXTR”

Push notifications:
Every mention of “Tari” —> “XTR” Every mention of “testnet Tari” —> “tXTR”

---

@Jasonvdb commented on [Fri Apr 24 2020](https://github.com/tari-project/wallet-ios/issues/312#issuecomment-618895865)

@talmahaj Some places missed where I also went ahead and updated:
- `Sorry, you cannot send tXTR to yourself`
- `Scan a Tari QR code to send tXTR to the recipient.`
- Action button (not CTA modal) on home screen `Send tXTR`
- Long press on app icon from home screen `Send tXTR`

Please let me know if any of those are ones I should not have updated ☝️ 

---

@Jasonvdb commented on [Fri Apr 24 2020](https://github.com/tari-project/wallet-ios/issues/312#issuecomment-618903244)

@talmahaj this is all config based so we've got the display name "testnet XTR" and the ticker "tXTR" and every reference to "Tari" as money now uses one of those 2 options. 

The one piece of copy to change that isn't consistent with the others is "XTR wallet". XTR refers to the mainnet currency so maybe that's misleading? I used "tXTR wallet" instead but if I'm wrong let me know and I'll change it back?

---

@talmahaj commented on [Fri Apr 24 2020](https://github.com/tari-project/wallet-ios/issues/312#issuecomment-619258047)

> @talmahaj this is all config based so we've got the display name "testnet XTR" and the ticker "tXTR" and every reference to "Tari" as money now uses one of those 2 options.
> 
> The one piece of copy to change that isn't consistent with the others is "XTR wallet". XTR refers to the mainnet currency so maybe that's misleading? I used "tXTR wallet" instead but if I'm wrong let me know and I'll change it back?

Per our call today this is totally fine!

**Comment by Tas4tari** [comment]
@kukabi @nyarian 
i do not see the following animation from the requirement above:
Sending animation
“Sending [amount] Tari” —> “Sending [amount] tXTR”
Is this no longer valid because of this issue: https://github.com/tari-project/tari/issues/1707

**Comment by Tas4tari** [comment]
Tested successfully on Huawei P30 lite, just waiting for confirmation of Push notification copy before closing

**Comment by Tas4tari** [comment]
Tested on Huawei P30 Lite:
@kukabi @talmahaj Differences picked up:
Sorry, you cannot send tXTR to yourself: Android displays as XTR
Scan a Tari QR code to send tXTR to the recipient.: Android displays as XTR
Long press on Icon on homescreen: Displays as XTR
Push Notifications display as XTR

**Comment by Tas4tari** [comment]
Tested on Huawei P30 Lite:
Sorry, you cannot send tXTR to yourself: Android displays as tXTR
Scan a Tari QR code to send tXTR to the recipient.: Android displays as tXTR
Long press on icon on home-screen:Displays as Tari Aurora
Push Notifications: Says Tari Aurora

**Comment by Tas4tari** [comment]
![Screenshot_20200525_101911_com whatsapp](https://user-images.githubusercontent.com/50987039/82794868-7172d480-9e73-11ea-9d5e-028acdc19644.jpg)
![Screenshot_20200525_095747_com tari android wallet](https://user-images.githubusercontent.com/50987039/82794884-78014c00-9e73-11ea-996b-aa7143741dad.jpg)
![Screenshot_20200525_095732_com tari android wallet](https://user-images.githubusercontent.com/50987039/82794902-7cc60000-9e73-11ea-9dd3-998391069bc2.jpg)
![Screenshot_20200525_103223_com huawei android launcher](https://user-images.githubusercontent.com/50987039/82794914-818ab400-9e73-11ea-8e24-6a79adf00ce8.jpg)

**Comment by Tas4tari** [comment]
![Uploading Screenshot_20200525_095819_com.huawei.android.launcher.jpg…]()
