### ISSUE TITLE
Launch QA: One of the user's emoji ID icons does not display on Android 7

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-android#315]
**Description**
One of the user's emoji ID icon does not display on the Send Transaction screen when pasting

**Reporter Telegram username:**
@pussinboots

**Device Details:**
Android 7.0

**Screenshots:**
![photo_2020-04-29 12 28 55](https://user-images.githubusercontent.com/50987039/80586518-5bf5c080-8a15-11ea-81b5-d71bdfaa103b.jpeg)
![photo_2020-04-29 12 28 42](https://user-images.githubusercontent.com/50987039/80586542-64e69200-8a15-11ea-8729-3c5e7868703e.jpeg)

**Comment by kukabi** [comment]
@Tas4tari @talmahaj Now that it's certain that the emoji set is going to change for better compatibility, can we close this issue or move it somewhere?
