### ISSUE TITLE
Privacy Mode

### ISSUE THREAD

**Issue by trymeouteh** [tari-project/wallet-android#317]
Please make Aurora Android not require any propietary code such as GApps and release the app on FDroid with updates for the privacy minded Android users who have degoogled Android devices. Monerujo wallet works on degoogled and can be downloaded on FDroid. Please allow degoogled users to access Aurora.

**Comment by kukabi** [comment]
Thanks a lot for the input @trymeouteh! We will take it into consideration. We don't use any proprietary components or libraries AFAICT, but we will still need to go through the code to make sure. Your feedback on the code regarding this issue is much welcome.

**Comment by kukabi** [comment]
As a note: https://f-droid.org/en/docs/Inclusion_Policy/

**Comment by Tas4tari** [comment]
@kukabi @nyarian Tested the Privacy with an apk file that @nyarian provided.

- There was no Tari enrollment (Did not receive Tari from the Bot)
- My session was not tracked on Matomo

As per @nyarian This is all correct in terms of testing the privacy

**Comment by Tas4tari** [comment]
FDroid compliancy: Generic solution as per discussion in stand up @Tas4tari to breakl uo this into a new ticket
