### ISSUE TITLE
Log files getting too large.

### ISSUE THREAD

**Issue by kukabi** [tari-project/wallet-android#318]
We need to find a way to delete the large log files.

**Comment by Tas4tari** [comment]
Moved to release 0.0.5

**Comment by Tas4tari** [comment]
Tested on Huawei P30 lite, app version 0.4.1
As per @kukabi this is working as expected as per the comment and screenshot below:
A clean install takes up around 83 mb initially
+13 megs in 2 days is reasonable  
max log size is 30 megs
so around 115 megs is still good
**Screenshot:**
![photo_2020-09-09 12 04 39](https://user-images.githubusercontent.com/50987039/92590900-4636b880-f29d-11ea-91b0-70d552d0728d.jpeg)
