### ISSUE TITLE
Emoji Compatibility

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-android#320]
Add emoji compatibility support libraries

https://developer.android.com/guide/topics/ui/look-and-feel/emoji-compat

**Comment by nyarian** [comment]
Jetpack Emoji Compat library seem to possess several bugs related to the emojies rendering inside a text view with custom font or letter spacing attribute specified: https://issuetracker.google.com/issues/155536607

At the moment the solution with yhe bundled font supporting Unicode 10 emojies list ( https://www.google.com/get/noto/help/emoji/ ) is introduced

**Comment by kukabi** [comment]
@Tas4tari @talmahaj Now that it's certain that the emoji set is going to change for better compatibility, can we close this issue or move it to somewhere else?
