### ISSUE TITLE
Relax internet connectivity check

### ISSUE THREAD

**Issue by kukabi** [tari-project/wallet-android#322]
Have less strict connectivity requirements, so the users with a network connection don't see "can't connect to the internet" dialog before it's certain that they don't actually have internet connection.

**Comment by Tas4tari** [comment]
@kukabi How do we test this?

**Comment by Tas4tari** [comment]
Test on browser-stack with network throttle option

**Comment by Tas4tari** [comment]
@kukabi Tested via browser-stack using the attached parameters and did not see the internet error. Also tested on my device without any internet connection to ensure I received the error.
<img width="1546" alt="Screen Shot 2020-05-14 at 3 25 44 PM" src="https://user-images.githubusercontent.com/50987039/82219590-ca93b300-991d-11ea-920f-4c18f9077f1b.png">
