### ISSUE TITLE
Disable Matomo tracking while in debug.

### ISSUE THREAD

**Issue by kukabi** [tari-project/wallet-android#331]
Currently it tracks regardless of the build configuration.

**Comment by Tas4tari** [comment]
Currently installing the apk file that @nyarian has sent through. Once installed will be able to confirm tracking

**Comment by Tas4tari** [comment]
Tested successfully on Huawei P30 Lite, event were not tracked when the apk file was installed.
Checked the Visitors log, the real time view and the events and this did not display at all.
**Screenshots below:**
<img width="1552" alt="Screen Shot 2020-05-12 at 4 45 52 PM" src="https://user-images.githubusercontent.com/50987039/81706302-3b475500-9470-11ea-9ee4-31c2fcd607f4.png"> 

<img width="1552" alt="Screen Shot 2020-05-12 at 4 46 04 PM" src="https://user-images.githubusercontent.com/50987039/81706294-3a162800-9470-11ea-8f19-6c2f74190d39.png">

<img width="1552" alt="Screen Shot 2020-05-12 at 4 46 16 PM" src="https://user-images.githubusercontent.com/50987039/81706254-32568380-9470-11ea-8755-16252a7a964f.png">
