### ISSUE TITLE
Launch QA: Enter Amount Screen UI issue when not enough Tari message is displayed

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-android#332]
**Description:**
A user on Telegram has reported that the "Not enough XTR..." alert overlaps the amount entered when the user tries to send more Tari than he has.

**Device:**
Sony X compact

**Reporter:**
Luigi626

**Screenshot:**
![photo_2020-05-05 09 40 12](https://user-images.githubusercontent.com/50987039/81049607-d3689b80-8ebe-11ea-82d8-5e4bbff3aafb.jpeg)

**Comment by nyarian** [comment]
@kukabi @Tas4tari
Wireframes for devices with small resolutions are necessary in order to proceed, to the ticket is moved to "Up Next" for now.

**Comment by Tas4tari** [comment]
@talmahaj  Would you and Karim be able to assist with this

**Comment by kukabi** [comment]
I'm working on a fix for smaller devices, it's an issue with most of the screens. I'll post screenshots here once it's complete. @Tas4tari @talmahaj

**Comment by Anziskavds** [comment]
Tested successfully on Android on a Samsung S9 on the Prod version 0.1.15.

![Screenshot_20200617-152651_Tari Aurora.jpg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/829efb7a-1f4c-42c0-8e33-99f7ddfe006c)
