### ISSUE TITLE
Tablet support

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-android#334]
@talmahaj commented on [Tue May 05 2020](https://github.com/tari-project/wallet-ios/issues/351)

@talmahaj commented on [Tue May 05 2020](https://github.com/tari-project/tari/issues/1821)

**Comment by kukabi** [comment]
@talmahaj Android wallet runs fine on tablets, I had a quick run on one of the tablets available on BrowserStack and it's looking fine to me. @tas4tari can you please confirm? You may test it with the following tablet devices on BrowserStack. I'm moving this issue under UAT.

![Screen Shot 2020-05-07 at 14 59 57](https://user-images.githubusercontent.com/2969501/81291964-73ffbc80-9073-11ea-8d05-47c70cb6e867.png)

**Comment by Tas4tari** [comment]
Tested via broser-stack, Wallet runs fine, videos attached
Samsung Galaxy Tab S6:
https://www.loom.com/share/2ba68efd545b430783a596e6edfda136
With a transaction:
https://www.loom.com/share/c699530dc34c444ba8a4dfcbda9407fb

**Comment by Tas4tari** [comment]
Tested via browser-stack, Wallet runs fine, video attached
**Galaxy Tab S5E:**
https://www.loom.com/share/148e560f85c84e65a106981f8175d878

**Comment by Tas4tari** [comment]
Tested via browser-stack, Wallet runs fine, video attached
**Galaxy Tab S4:**
https://www.loom.com/share/ad899c294ded49979ad8b83882038278

**Comment by Tas4tari** [comment]
Tested via browser-stack, Wallet runs fine, video attached
**Galaxy Tab S3, Android 7:**
https://www.loom.com/share/068a6ba088de47fa96aacff85fd48f3e

**Comment by Tas4tari** [comment]
Tested via browser-stack, Wallet runs fine, video attached
**Galaxy Tab S3, Android 8:**
https://www.loom.com/share/a3ec8e9ca0b940c79597fc18fd0748b9
