### ISSUE TITLE
Long press "Copy" button on emoji ID to copy pubkey

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-android#335]
Great idea by Jay for a bandaid solution to the problem where the Emoji ID renders as images instead of emoji when pasted in certain apps: 

- When user **long presses** on the copy button, instead of copying the emoji ID, it should copy the alphanumeric pubkey into the clipboard. (When the user's recipient adds it to clipboard, it will display as an emoji ID again in their app)

In the future, we'll have a settings screen where pubkeys will be more explicit/discoverable, but in the meantime we can at least share this feature with users on telegram who are struggling

**Comment by Tas4tari** [comment]
**Tested on Huawei P30 lite:**

- When user long presses on the copy emoji button the pubkey is successfully copied
- When user pastes the pubkey into and IOS device, it successfully displays the emoji ID
- When user copies pubkey into and Android OS10 device, it copies the pubkey and does not display the emoji ID

**IOS Device:**
![IMG_DCE7A18CBC98-1](https://user-images.githubusercontent.com/50987039/82794330-99156d00-9e72-11ea-946e-2a95d60ef26f.jpeg)

**Android device:**
![Image Pasted at 2020-5-25 10-02](https://user-images.githubusercontent.com/50987039/82794423-bea27680-9e72-11ea-90f3-bd14403ef539.png)
