### ISSUE TITLE
QA: Push Notifications: When user selects the push notification , the TDR screen they are redirected to is incorrect

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-android#343]
**Description:**
As a user I found that when a user sends me Tari, when I click on the push notification I am redirected to the Transactions Details screen for the incorrect transaction.

**Steps:**

1. User sent me 35 Tari
2. I received the push notification
3. I am redirected to the Transaction Details screen on the app
4. When I view the details on the TDS, I find that it is for the first transaction that is pending from this morning and not for the 35 Tari that was sent.

**Additional Notes:**
This is reproducible on version:  v0.1.10-jnLibs-0.9.1 (Beta)

**Another possible issue:**
When the user selects the Push notification and is redirected to the TDS within the wallet, when he selects the back button, instead of redirecting to the user's Wallet home-screen, he is redirected out of the app, which is also reproducible.

**Device:**
Huawei P30 lite

**Screenshots:**

**Push Notification received:**
![Screenshot_20200507_152209_com huawei android launcher](https://user-images.githubusercontent.com/50987039/81300102-85e35e80-9077-11ea-856a-960bf4f56cb4.jpg)
**When I clicked on the Push Notification, this is where I am redirected to:**
![Screenshot_20200507_152216_com tari android wallet](https://user-images.githubusercontent.com/50987039/81300171-9bf11f00-9077-11ea-9aaa-1acf4b5a1e31.jpg)

**Comment by nyarian** [comment]
@Tas4tari the bug with back button leaving the app when on `Tx Details` page was resolved, but could't reproduce the issue with wrong TX opening. Can you confirm if this behavior is still here?

**Comment by kukabi** [comment]
@Tas4tari moving this back to UAT as well, please check if it persists. @nyarian

**Comment by Tas4tari** [comment]
@kukabi @nyarian Tested successfully on Huawei P30 lite, issue no longer persists
