### ISSUE TITLE
Minor copy change from "XTR" to "tXTR"

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-android#346]
Please change copy "XTR" to "tXTR" in this modal

![Screen Shot 2020-05-08 at 4.54.30 PM.png](https://images.zenhubusercontent.com/5d361e1d286eff0dc8805d38/2f873293-e419-42fa-a0cd-e09c8cc5ac05)

**Comment by Tas4tari** [comment]
Tested successfully on Huawei P30 lite:
![Screenshot_20200525_104434_com tari android wallet](https://user-images.githubusercontent.com/50987039/82795869-ea266080-9e74-11ea-8a4a-1ae25c1fd2af.jpg)
