### ISSUE TITLE
Continually Crashing after login

### ISSUE THREAD

**Issue by Cyebit** [tari-project/wallet-android#347]
Tari Aurora wallet now continually crashes 10 seconds after login, I've even had to write this feedback several times from app as it crashed when I pressed send feedback so I'm not sure if crash report is being sent when I press "send" as it just exits/closes when I press "send" without confirmation. I'm using Android Samsung S8+ phone. I can view the crash report but it does not give me an option to save the report. Ive tried to uninstall & reinstall Tari Aurora wallet app but same issue occurs again. 
The issues seemed to start after I downloaded the Fusion cryptocurrency wallet from wedefi.com and after I installed their apk file, during setup I decided to uninstall their app as it would not verify. The crashing of Tari Wallet seemed to then start after this. Currently Tari Aurora wallet version v0.1.10-jniLibs-0.9.1

**Comment by nyarian** [comment]
Hey, @Cyebit
Would it be possible to post the crash report as a screenshot?

**Comment by Tas4tari** [comment]
@Cyebit Is this issue still occurring on your device? If so can you please provide the crash report as a screenshot if you are unable to send via the bug reporting email.
Thanks!

**Comment by Cyebit** [comment]
> @Cyebit Is this issue still occurring on your device? If so can you please provide the crash report as a screenshot if you are unable to send via the bug reporting email.
> Thanks!

Everything appears to be working 100% now due to fixes already done. Thank you for your help 😀👍
