### ISSUE TITLE
QA: Transactions List: Scrolling: Scrolling through transaction list isn't very smooth or consitstent

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-android#353]
**Description:**
As a user who has multiple transactions, I find that when I'm scrolling through the transaction list, the scroll sometimes get's stuck and at other times it seems to skip through multiple transactions and is therefore not consistent nor smooth

**Device:**
Huawei P30 lite

**App versions:**
v0.1.11-jnLibs-0.9.2

**Comment by Tas4tari** [comment]
**Tested on Huawei P30 lite on v0.1.14**
The transaction list scrolling still gets stuck in some places and jumps when the user is scrolling back up, I have attached a video, hopefully this helps.
**Video:**
https://drive.google.com/file/d/1zsQ-dt2ZTZ8WPbiXgtYJ1y1HLYXzrVDj/view?usp=sharing

**Comment by Tas4tari** [comment]
Tested on Huawei P30 lite, with the new android build from Android Studio. Tested by using the "make it rain" command that added a 100 transactions to the wallet. Scrolling on the Transactions List screen is now smooth and easy.
https://drive.google.com/file/d/1hFgytLiACAef92GMMNCNSqfmoqN3HLxl/view?usp=sharing

**Comment by Anziskavds** [comment]
Testing in progress. I don't have a lot of transactions to test this. I am trying to get a few transactions to test this. Testing on Android Prod version 0.1.15 on a Samsung S9.

cc @Tas4tari Tas if you still have that many transactions and I didn't manage to get a few transactions by tomorrow, would you mind testing this again after you updated to version 0.1.15?

**Comment by Anziskavds** [comment]
Tested successfully on Android version 0.1.15 on a Samsung S9.

https://share.getcloudapp.com/KouBwQNl
