### ISSUE TITLE
Crash on configuration change during Tari sending journey

### ISSUE THREAD

**Issue by nyarian** [tari-project/wallet-android#364]
Steps to reproduce:
 - Navigate to any screen falling into `Send Tari Journey` (`add recipient` will do)
 - Change the configuration of the device (day\night mode will do as well as language change, font size change, minimal DP - anything)
 - The app should crash

**Comment by Tas4tari** [comment]
**Tested on Huawei P30 lite:**

1. Tested in the Add recipient screen
2. Tested on the Add amount screen
3. Tested on the Add note screen

On all of these cases, I tested by changing via dark mode, and changing device font size etc and the app did not crash

cc @nyarian
