### ISSUE TITLE
Configure obfuscation rules to reduce the APK size

### ISSUE THREAD

**Issue by nyarian** [tari-project/wallet-android#365]

**Comment by Tas4tari** [comment]
Tested with the Android Studio Internal Build, user can successfully:

- Complete the onboarding process
- Send and receive transactions
- Navigate to the TTL store
- Navigate to the TDS
- Save contact name
- View the eMoji ID and QR code
- Cancel transactions

**Comment by kukabi** [comment]
Current production release (b116):
![Screen Shot 2020-06-22 at 15 57 44](https://user-images.githubusercontent.com/2969501/85290187-42b34280-b4a1-11ea-80b3-9db552f4c8bb.png)

0.2.0 beta release (b120):
![Screen Shot 2020-06-22 at 15 58 05](https://user-images.githubusercontent.com/2969501/85290207-4b0b7d80-b4a1-11ea-88d2-214ce4674f59.png)

APK size reduced.
