### ISSUE TITLE
Matomo reports page navigation event on each configuration change

### ISSUE THREAD

**Issue by nyarian** [tari-project/wallet-android#366]
Steps to reproduce:
 - Navigate to any screen for which a corresponding Matomo event is being sent
 - Change configuration of the device
 - An additional Matomo event should be logged concerning the screen that was current on configuration change

**Comment by Tas4tari** [comment]
Tested successfully on Huawei P30 Lite, changed font size and from Light mode to Dark mode. No duplicate events were logged on Matamo: 
https://www.loom.com/share/8bd3077a1cb14030870f4b0f2b55919a
