### ISSUE TITLE
Discussion: Release APK builds

### ISSUE THREAD

**Issue by kukabi** [tari-project/wallet-android#368]
This idea/request came from the user `Mochi101` on Telegram via the IRC bouncer: shall we make APK releases of the Android app (both private and regular builds)?

**Comment by nyarian** [comment]
That would be nice IMHO. Without a keystore for private builds available right in the repository it is quite tedious for an average user to build the app, as it requires certain skills and knowledge that he might not posses in the first place. Also such users just might now know that they can just build the app themselves (the ones that just install the app from PlayMarket and don't pay much attention to the community).

**Comment by kukabi** [comment]
As of v0.2.0 we are building regular and private APK releases. Distribution channel is not clear yet, we can close this issue once distribution too gets sorted out.

**Comment by Tas4tari** [comment]
@kukabi Since this has been done and we are currently just looking for an effective Distribution process, can I move this over to In Progress?

**Comment by kukabi** [comment]
@Tas4tari yep, moved it.

**Comment by kukabi** [comment]
Latest Play Store, GitHub and BrowserStack releases were made by the automated [release workflow](https://github.com/tari-project/wallet-android/blob/development/.github/workflows/release-workflow.yml). @tas I think we can close this issue, let's talk next week regarding the handover to QA.

**Comment by Tas4tari** [comment]
@kukabi Based on above comment, I'm closing off this issue.
