### ISSUE TITLE
User unable to use the app as Internet error keeps being received

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-android#369]
**Description:**
Hi,

I was able to send Tari in first days of launch. But since last week, I keep getting this error message as appended screenshot. Even I could send a test tx, it never go through. I have tried restart, reinstall to last version, change networks. I don't use anything likes VPN. So I couldn't figure out what happened.

**Reporter:**
Chun-hsi Tso

**Device:**
Android

**Platform:**
Bug report submitted

**Logs:**
[ffi_logs_DE016E050D2348ECABA1CCF84061616A4AAF82451DE912760B71B8AF6FEA6473.zip](https://github.com/tari-project/wallet-android/files/4628012/ffi_logs_DE016E050D2348ECABA1CCF84061616A4AAF82451DE912760B71B8AF6FEA6473.zip)

**Screenshot:**
![Screenshot_20200514-085010](https://user-images.githubusercontent.com/50987039/81930222-969c5300-95e8-11ea-994e-9c3a9fabfdcb.jpg)

**Comment by kukabi** [comment]
This was fixed by #351, it will be released with today's internal release, moving to UAT. @Tas4tari

**Comment by Tas4tari** [comment]
Thanks I've added it to this week's release version :)

**Comment by Tas4tari** [comment]
Have not received the Internet connectivity error as stated above on v0.1.13
Only received the error when I had switched of my wifi and mobile data
cc @kukabi
