### ISSUE TITLE
Notification misdirect

### ISSUE THREAD

**Issue by hansfordj** [tari-project/wallet-android#390]
Opening a notification of a new transaction directs to an old transaction with past message.
Showing "Waiting for sender to complete transaction" for the previous transaction that is confirmed.

**Comment by kukabi** [comment]
Thanks for the report @hansfordj. What version is your app? It looks like a duplicate of https://github.com/tari-project/wallet-android/issues/343, so it might be resolved with one of the more recent versions.

**Comment by Tas4tari** [comment]
Tested the push notification redirect on v0.1.14: Tested sucessfully
https://drive.google.com/file/d/1p1KvqF1PKfGDsgUfHrW362uNuNH85l-a/view?usp=sharing
