### ISSUE TITLE
Battery Consumption: Users are killing the app in an attempt to conserve their battery

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-android#397]
**Description:**
Seen a few people saying they're killing the android foreground service to conserve battery. 

**Solution to look at:**
Maybe we need to consider waking it up with remote push notifications and closing it when it hasn't been used in a while?

**Comment by Tas4tari** [comment]
Another user has submitted a bug report for app draining battery
**Description:**
battery draining a lot in background

**Logs:**
[ffi_logs_B0DF62A16DA49996CB8B40018891C308F45486B8B23CBAD6850B661ADE392632.zip](https://github.com/tari-project/wallet-android/files/4699935/ffi_logs_B0DF62A16DA49996CB8B40018891C308F45486B8B23CBAD6850B661ADE392632.zip)


**Screenshot:**
![Screenshot_20200529-065725](https://user-images.githubusercontent.com/50987039/83226825-1dbdff00-a183-11ea-92e2-55c537ea79fd.jpg)

**Comment by Anziskavds** [comment]
Tested successfully on Android on version 0.1.15 on a Samsung S9. Battery usage is much better than what it was.![Screenshot_20200618-143606_Device care.jpg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/7f686e34-49b6-49b7-83b0-01c6991ffa30)
