### ISSUE TITLE
Add API key to push server signed requests

### ISSUE THREAD

**Issue by Jasonvdb** [tari-project/wallet-android#399]
I've improved the push notification server by adding a secret API key that the apps need to prepend to the message they sign. This key needs to be injected when compiling and not committed.

[Push server example](https://github.com/tari-labs/ios_aurora_push#send-a-push-notification-to-transaction-recipient)

The old method of sending will still work for now but after giving people enough time to update the app we can remove the deprecated validation check.

**Comment by nyarian** [comment]
@Jasonvdb what about users that want to assemble private build themselves using the sources from android app repo?

**Comment by Tas4tari** [comment]
As per @Jasonvdb "If an android can send a notification to ios then it's all good" however no notification was received on IOS
cc @nyarian @Anziskavds

**Comment by Tas4tari** [comment]
As per @Jasonvdb 
Ok seeing that request fail to authenticate so there is an issue, will chat to Kutsal

Moving back to Up Next

**Comment by Jasonvdb** [comment]
Push server is showing a status 403 which means `Invalid request signature` in this case

**Comment by kukabi** [comment]
@Tas4tari it should be fixed with the latest update I uploaded today.

**Comment by Tas4tari** [comment]
Will retest now

**Comment by Tas4tari** [comment]
Tested by sending a push notification from Android to iOS, tested successfully.
