### ISSUE TITLE
Update project README

### ISSUE THREAD

**Issue by kukabi** [tari-project/wallet-android#402]
README is getting out of date, it should be updated with the new build configuration and flow for Mac OS X Catalina and Mojave, Windows 10 and a Linux system (Ubuntu?).

**Comment by nyarian** [comment]
It might me useful to have root README file for people that are curious about the project or want to assemble private build and create a separate, more technical README for contributors. What do you think, @kukabi @talmahaj?

**Comment by talmahaj** [comment]
I'll defer to you guys as well as @Jasonvdb and @CjS77 on this one!

**Comment by Tas4tari** [comment]
@kukabi Can you please let me know where I can find the README file and how do I determine what content it needs to cover in order to adequately test this?

**Comment by kukabi** [comment]
@Tas4tari you may view the README file at the [repo index page](https://github.com/tari-project/wallet-android). I think we can just close this issue. You can test the build instructions but I guess you would need a clean installation for it - not sure if it's needed.

**Comment by Tas4tari** [comment]
@kukabi Ok will do. Closing this issue and will go through the read me document as well
