### ISSUE TITLE
[Feature] Backup and restore wallet: Back up with recovery phrase

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-android#406]
See [parent](https://github.com/tari-project/tari/issues/1906)

**Comment by talmahaj** [comment]
@Tas4tari I can't do it myself but we should move to backlog maybe until this is ready?

**Comment by Tas4tari** [comment]
@talmahaj Will do so

**Comment by alexandrVakhtinTari** [comment]
It's implemented now
