### ISSUE TITLE
[Feature] Backup and restore wallet: Restore wallet flow

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-android#409]
See [parent](https://github.com/tari-project/tari/issues/1906)

**Comment by Tas4tari** [comment]
@nyarian Can we move this to UAT for the Google Drive Restore process?

**Comment by nyarian** [comment]
@Tas4tari I'd say yes, as permission revoking handling, having non-critical nature, will just come in the next patch

**Comment by Tas4tari** [comment]
Tested successfully user was able to restore wallet

**Comment by Tas4tari** [comment]
**Huawei P30 Lite BackUp flow:**
https://drive.google.com/file/d/16t7qJF-c6E8aMHsvpvbNBY_KwJXXuhQ7/view?usp=sharing
**Huawei P30 Lite Restore flow:**
https://drive.google.com/file/d/1kWOlS9lfCKzYMhWVDNqcuzHJ-4GQ2Zx9/view?usp=sharing

**Comment by Tas4tari** [comment]
**Huawei P30 Lite BackUp flow:**
https://drive.google.com/file/d/16t7qJF-c6E8aMHsvpvbNBY_KwJXXuhQ7/view?usp=sharing
**Huawei P30 Lite Restore flow:**
https://drive.google.com/file/d/1kWOlS9lfCKzYMhWVDNqcuzHJ-4GQ2Zx9/view?usp=sharing
