### ISSUE TITLE
Implement automatic latest binaries version definition during project's dependencies resolving phase

### ISSUE THREAD

**Issue by nyarian** [tari-project/wallet-android#415]

**Comment by kukabi** [comment]
@nyarian At the moment we develop against a specific FFI version with a specific header, it might change in the future but it seems like for a while we have to explicitly set the FFI version in the gradle script. Let's close this issue if you agree.

**Comment by kukabi** [comment]
Closing this issue, please see my previous comment. @Tas4tari @nyarian
