### ISSUE TITLE
Emoji ID compatibility error handling

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-android#422]
Once we release a version of the wallet with a new emoji set, users on that version will not be able to transact with users on prior ones and vice versa. This means we'll need to show an error message for users who try to do so.

Implementation note from Cayle: In the mobile app, if you have a validation function, the existence of any deprecated emoji should trigger a warning, and suggest that the sender upgrade.

(MM conversation can be found here: https://nomatter.tari.com/tari-ext/pl/wquo3nb15jyu5jitzdn5eogcbr)

**Acceptance Criteria**
- When a user reaches the Add Recipient screen, AND the version is on the version with the new emoji set, AND has an old emoji ID in their clipboard, they should immediately see a standard alert pop up reading: "Emoji ID Update Required" "Your recipient needs to upgrade to the latest version of Tari Aurora and copy their updated Emoji ID to transact with you" "OK"

**Comment by talmahaj** [comment]
@kukabi did you see Jay's implementation here? I think displaying the error here is fine too. Whatever you and @Jasonvdb decide for both platforms works for me. https://github.com/tari-project/wallet-ios/issues/416

**Comment by kukabi** [comment]
@talmahaj yes, it shows the warning only when emoji id is pasted tho, I think we should keep it. I thought at least for a few versions we should display something (if not a dialog) as soon as the user enters the screen as well.

**Comment by Anziskavds** [comment]
Tested successfully on the Prod version 0.1.15 on a Samsung S9.

![Screenshot_20200617-155624_Tari Aurora.jpg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/7762c3e5-1a28-4dbc-b190-46f2147eb65e)
