### ISSUE TITLE
User should be able to tap clipboard banner to paste Emoji ID

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-android#424]
When I'm in the Select Recipient screen, and I have an emoji ID in the clipboard, I can tap on the toolip that appears above the clipboard banner to paste it. I expect to ALSO be able to tap the banner itself to paste the Emoji ID, which is not currently working.

**Acceptance Criteria**
Tapping on emoji ID clipboard banner pastes Emoji ID, just like tapping the tooltip label

**Comment by Tas4tari** [comment]
Tested successfully on the internal Android build from Android Studio on Huawei P30 lite, i can paste the emoji ID by selecting on the emoji ID banner itself instead of the "Paste copied Emoji ID" bubble
https://drive.google.com/file/d/1wFqXQ3Ued7TwCPNFrDBmqPH9Lzq2szJN/view?usp=sharing

**Comment by Anziskavds** [comment]
Tested successfully on Android on a Samsung S9 on the Prod version 0.1.15. I can paste the emoji ID by clicking on the emoji ID banner itself instead of the "Paste copied Emoji ID".

https://share.getcloudapp.com/xQuDDGk5
