### ISSUE TITLE
Change base node on sync failure.

### ISSUE THREAD

**Issue by kukabi** [tari-project/wallet-android#439]
Currently the base node is set only at app startup and remains the same. Randomize the list of base nodes and do a round-robin rotation on base node sync failure.

**Comment by Anziskavds** [comment]
@kukabi Do you perhaps have any steps for me on how to test this?

**Comment by kukabi** [comment]
@Anziskavds When you go to the debug screen you'll find the base node settings tab. You can take note of the current base node from that tab. Go back to home screen and try to get the "it's not you it's the network" error. Base node setting should change after this error, so if you go back to the base node settings you should see a different base node address & key.

**Comment by Anziskavds** [comment]
Tested successfully on Android version 0.2.0 on a Samsung S9.

![Screenshot_20200623-135221_Tari Aurora.jpg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/06651e7f-effb-4b4e-8544-dd82442df0fd)


![Screenshot_20200623-135337_Tari Aurora.jpg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/734d3761-4d44-4b45-9e69-37c6847f40ea)
