### ISSUE TITLE
Add "Report a Bug" to Settings

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-android#452]
Add ability to report a bug to settings in case users do not know about shake to report feature.

**Acceptance Criteria**

- On Settings Screen, new item should appear at the top of More section reading "Report a Bug"
- Tapping item should open the same email template as doing so from shake-to-report screen

**Comment by Tas4tari** [comment]
Tested successfully on Huawei P30 lite
App version: v0.3.0-jnLibs-0.15.2
**Video**
https://drive.google.com/file/d/1IB-X05bR6Eibr01AO675bPkAoiGO5bjZ/view?usp=sharing
**Screenshot fo bug report received successfully:**
![Screen Shot 2020-07-16 at 9 22 11 AM](https://user-images.githubusercontent.com/50987039/87640335-d8f82280-c746-11ea-86fc-38d71e26eedb.png)
