### ISSUE TITLE
FFI instrumented test suite improvement and CI integration

### ISSUE THREAD

**Issue by kukabi** [tari-project/wallet-android#455]
Our instrumented FFI tests are not running on CircleCI at the moment, and because of this we're not able to track the status of tests on PRs pre-merge. Tests get out of date quickly since we don't have the FFI tests as part of our process.

We should have a comprehensive and well-kept suite of instrumented FFI tests and be able to run them on CircleCI.

**Comment by Tas4tari** [comment]
Moved to release 0.0.5

**Comment by kukabi** [comment]
@Tas4tari this improvement is code-only issue and is not testable outside of Android Studio, closing it.
