### ISSUE TITLE
Create JNI bindings for Rust libWallet

### ISSUE THREAD

**Issue by CjS77** [tari-project/wallet-android#46]
Create a JNI wrapper for the c-library exported by [the rust libwallet library](https://github.com/tari-project/tari/blob/development/base_layer/wallet_ffi/src/lib.rs).

**Comment by Tas4tari** [comment]
#49

**Comment by Tas4tari** [comment]
#50

**Comment by CjS77** [comment]
Closing this in favour of vertical development on UI tickets to incorporate foreground service and JNI bindings.
