### ISSUE TITLE
App Notifications

### ISSUE THREAD

**Issue by Zaheero11** [tari-project/wallet-android#464]
The Tari Aurora app is constantly running in the background even when the app is not in use.  I understand that this is by design.  However, i'm constantly getting notifications that the "app is running in the background".  How do we disable this without having to force stop?

**Comment by Tas4tari** [comment]
@Zaheero11 You could try disabling notifications for the app via Settings on your device

**Comment by nyarian** [comment]
Hi @Zaheero11
Presence of an application-generated notification in the system tray is a requirement imposed by Android OS starting from 8 version (and later) - background services without these notifications will be killed by the operating system if the application (UI part) gets backgrounded or destroyed (so it's like a musical player here - a notification will be always present, as it's the guarantee that OS won't kill the background job and stop the music even if the UI part was explicitly destroyed by the user).

![android_foreground_notification](https://user-images.githubusercontent.com/34913433/90522508-78f50180-e174-11ea-922d-0f7aef4d53e7.png)
