### ISSUE TITLE
Base Node Setting Screen Should Accept onion v2 Addresses

### ISSUE THREAD

**Issue by kukabi** [tari-project/wallet-android#466]

**Comment by kukabi** [comment]
`onion3` base node sample:

`b81b4071f72418cc410166d9baf0c6ef7a8c309e64671fafbbed88f7e1ee7709::/onion3/lwwcv4nq7epgem5vdcawom4mquqsw2odbwfcjzv3j6sksx4gr24e52ad:18141`

**Comment by kukabi** [comment]
`onion v2` base node public key / address sample:

`a81b4071f72418cc410166d9baf0c6ef7a8c309e64671fafbbed88f7e1ee7709::/onion/gem5vdcawom4mquq:18141`

**Comment by Tas4tari** [comment]
Tested with the Regular release apk, on Huawei P30 Lite, when address is added and saved, it says peer saved successfully:
**Onion v2:**
https://drive.google.com/file/d/1ip8Wc1oBZrVTu7bzoug53jYy5XBZCLf5/view?usp=sharing
**Onion v3**
https://drive.google.com/file/d/1BdW9a0MhZw98Pq9_8TjcMAptbY7It2QL/view?usp=sharing
@kukabi Please let me know if i've tested this correctly, I've posted the videos for both the addresses

**Comment by kukabi** [comment]
@Tas4tari yep they're both looking correct.

**Comment by Tas4tari** [comment]
Tested successfully on the Beta Release
