### ISSUE TITLE
Backup and Restore: Restore Wallet screen: Encrypted and Unencrypted backup flow

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-android#474]
**Description:**
Currently when the user selects "Restore an existing wallet", the screen displayed is the "Enter a password" screen with the Restore Wallet button enabled.
The button here is enabled so that if a user did not encrypt their back up, they could select the button to Restore their existing unencrypted back up, however this can be misleading to users.

**Acceptance criteria**

- If a user has an unencrypted back up, do not display the "Enter your backup password" screen and take them through the old restore flow where they are redirected to "Restore your wallet" screen when they select "Restore an existing wallet" on the splash screen: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5ecc7ca7af080a47b6f889f7 : **Working currently**
- If the user has an encrypted back up, display the "Enter your backup password screen, with the Restore Wallet button disabled until they have typed in a password:https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5efed39ea33ceab928ffca25

@nyarian Please let me know if this is understandable

**Comment by kukabi** [comment]
Tested the app, password entry screen does not get displayed for a non-encrypted password.

Password validation should not be done when entering password, it would give a clue about the password. Current behavior of enabling the button after a single character is entered seems to be good.

Moving the issue to UAT.

**Comment by Tas4tari** [comment]
**Test Scenarios:**

- User has an unencrypted wallet and does a Restore (No Enter password screen should display)
- User has an encrypted wallet and does a restore:

> Enter Password screen should display
> Restore Wallet button should be disabled
> When user enters a character into the Enter Password field, the Restore Wallet button should be automatically enabled

**Comment by Tas4tari** [comment]
@nyarian @kukabi Tested unsuccessfully, the Restore Wallet button is still enabled: App version: v0.3.0.-jnLibs-0.16.0
https://drive.google.com/file/d/11_HgQKECvHRj3RhR0AIA_qySlHX9ZszW/view?usp=sharing

**Comment by Tas4tari** [comment]
Tested unsuccessfully, the Restore Wallet button is still enabled: App version: v0.3.0.-jnLibs-0.16.0
https://drive.google.com/file/d/1cOJYAiOoDBMXmRh5ma7jixn1cQt2pJoQ/view?usp=sharing

**Comment by Tas4tari** [comment]
Tested successfully using the apk Regular release build on Huawei P30 Lite:

**Comment by Tas4tari** [comment]
**Tested successfully on the Beta release:**
**Before Restore:**
https://drive.google.com/file/d/1Csz8boMlQRKH6oZlqQ0je3t-ozcI7srT/view?usp=sharing
**After Restore:**
https://drive.google.com/file/d/1Wl9fXu9GXT1u_RJoAXHM0qeuv6IdGoXF/view?usp=sharing
