### ISSUE TITLE
Create ForegroundService for libwallet

### ISSUE THREAD

**Issue by CjS77** [tari-project/wallet-android#48]
The Tari Android wallet will obtain wallet services from the Tari blockchain via a foreground service.

This foreground service should only be accessible from whitelisted apps (or some other suitable authentication process).

The foreground service will monitor the blockchain via libwallet and a connected base node to update the UI application about:
* New incoming transactions and messages
* Completed outgoing transactions
* Newly mined blocks containing transactions I'm interested in

See also #46

**Comment by kukabi** [comment]
Currently the service is exposed without security. We'll need to decide how to whitelist the apps. And there are more events listened to by the service listener, please see TariWalletServiceListener.aidl for the list of events - I can remove the events that are not needed.

**Comment by CjS77** [comment]
We can proceed for TestNet, but will have to implement a secure strategy before mainnet
