### ISSUE TITLE
Wallet Backups screen: Up to Date: Hide Backup now option when backups are enabled and Up to Date

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-android#481]
**Description:**

- Currently on Android we display the Backup Now option as disabled when the wallet is up to date, and iOS hides this from the user

**Acceptance Criteria:**

- When the wallet backup is Up to Date and automatic backups are enabled, hide the "Back up now" option as it is on iOS.
- Screens of both Android and iOS have been added for reference

**iOS**
![up_to_date_ios](https://user-images.githubusercontent.com/50987039/87959463-3972c100-cab3-11ea-8339-12d057968750.png)

**Android**
![up_to_date_android](https://user-images.githubusercontent.com/50987039/87959478-3e377500-cab3-11ea-82b0-857b2e0dd305.png)

**Comment by nyarian** [comment]
@Tas4tari should the button be visible is the backup is scheduled?

**Comment by Tas4tari** [comment]
@kukabi Can best answer that

**Comment by Tas4tari** [comment]
Tested successfully on Huawei P30 lite, App version: v0.3.0-jnLibs-0.16.0
![photo_2020-07-24 09 48 56](https://user-images.githubusercontent.com/50987039/88370730-e9397e80-cd92-11ea-9a04-4125c8832342.jpeg)
