### ISSUE TITLE
Automated Backups: User is signed out of Google Drive: Error message is incorrect and no push notification is received by the user

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-android#483]
**Description of issue:**

- Tested by disconnecting the Drive
- Error message differs from the requirement below and no push notification is displayed to the user.
- User receives an error message that states "Cannot access Google Drive. Please make sure you are connected to the Internet and have given Aurora the necessary permission"
- Error message was only displayed when user tried to switch automatic backups on again as it was disabled when the user selected to disconnect the drive @kukabi @nyarian Should the error not have displayed when the user actually disconnected the drive?

**Video:**
https://drive.google.com/drive/folders/1h8a73G1y5BpDjfkPr84ZR7WLDX9ojFCR

**Expected Behavior:**

- **Modal reading:**  "Wallet Backup Incomplete" "Your iCloud storage is full"/"Your Google Drive is full" "OK"
- If user is signed out of iCloud/Google drive, show same push notif and modal as above but body of message should read: **"You are not signed into iCloud" or "You are not signed into Google Drive"**

**Testing:**

- Android tested by disconnecting the drive

**Comment by Tas4tari** [comment]
Tested on Huawei P30 Lite, App version: v0.3.0-jnLibs-0.16.0
**How this was tested:**

- User disconnected the Drive
- User went and enabled Toggle switch then cancelled on permissions to access the Drive
- When permissions were cancelled I received the error

**Results:**

- As a user i received the Modal correctly (See screenshot below) however I did not receive a push notification @kukabi Can you confirm if I should have received that push notification?

**Screenshot:**
![photo_2020-07-24 13 36 37](https://user-images.githubusercontent.com/50987039/88387432-b7381480-cdb2-11ea-8c36-f4b11af6a541.jpeg)

**Comment by kukabi** [comment]
@Tas4tari I don't think a push notification is required, user is informed through the modal dialog.
