### ISSUE TITLE
Automated backups: Google Drive disabled: Error message is incorrect and user did not receive push notification

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-android#484]
**Description of issue:** 

- Tested by Disconnecting app from the Drive 
- User receives an error message that states "Cannot access Google Drive. Please make sure you are connected to the Internet and have given Aurora the necessary permission" 
- Error message was only displayed when user tried to switch automatic backups on again as it was disabled when the user selected to disconnect the drive @kukabi @nyarian Should the error not have displayed when the user actually disconnected the drive?

**Video:**
https://drive.google.com/file/d/1vEkfm_4yOVgD3j0incrs1YYxfpAYt65T/view?usp=sharing

**Expected behavior:**
If user has cloud storage disabled, show same push notif and modal as above but body of message should read "You do not have iCloud enabled on your device" or "You do not have Google Drive enabled on your device"

**Comment by Tas4tari** [comment]
Please see comments here: https://github.com/tari-project/wallet-android/issues/483

**Comment by kukabi** [comment]
@Tas4tari User-triggered and scheduled backups are different: failed user-triggered ones will show a modal dialog, and failed scheduled ones will post a push notification.

**Comment by kukabi** [comment]
@Tas4tari sorry, please ignore my previous comment - I thought disabling GDrive (delete all account from device) and revoking auth through GDrive web apps are two different cases.
