### ISSUE TITLE
Shiny new bottom tab navigation

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-android#487]
@talmahaj commented on [Mon Jul 20 2020](https://github.com/tari-project/wallet-ios/issues/494)

See in-context specs posted as comments at zpl.io/2vJq1We

Nav should only appear on tx list screen

**Comment by Tas4tari** [comment]
Testing on Huawei P30 Lite, app version: 0.4.0:
**Requirements from design:**
- Nav should only appear on tx list screen: **Tested unsuccessfully. Nav appears on all pages on the app except when user selects to Send Transaction icon**
- Nav to tx list screen: **Tested successfully. When user selects the Home icon they are redirected to the Transaction List screen**
- Cart icon opens store modal: **Tested successfully, when user selects the Cart icon, the TTL store modal is opened**
- Multidirectional icon opens send tari flow: **Tested successfully. When user selects the icon they are taken to the Send Tari flow**
- Profile icon: nav to profile screen: **Tested successfully. When user selects the profile icon they are taken to their profile and the settings icon is no longer displayed in user's profile**
- Settings icon: Remove settings icon from profile screen -- it should only appear in nav now: **Tested successfully, when user selects the Settings icon they are now taken to the app Setting page**

**Video:**
https://drive.google.com/file/d/1c4vcAk5F6Cf6O_twpHlT9rTlURGqV78X/view?usp=sharing

**Comment by Tas4tari** [comment]
**From Mattermost:**
- Beyond that, we could have the nav display on JUST the primary navigation screens, but not their children (e.g. main settings screen, but not subsettings screen -- transactions list, but not transaction details). This is a pretty common pattern, for example go to your FB app, select the Profile nav item, and try to edit something in your profile -- the child screens under the primary ones do not display the nav.: **Tested successfully. Nav displays on all Primary screens and does not display in sub-setting screen or Transaction details screen**
