### ISSUE TITLE
Tx list screen design tweaks

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-android#488]
@talmahaj commented on [Mon Jul 20 2020](https://github.com/tari-project/wallet-ios/issues/495)

See in context specs at https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/dashboard?seid=5f167670e4bc278d51faf26d

(Note there is also one font color change on the tx detail screen)

**Comment by Anziskavds** [comment]
Tested successfully on Android on version 0.4.0 on a Samsung S9.

![Screenshot_20200806-192109_Tari Aurora.jpg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/82de81c3-18bb-4fec-a4c5-de437a49ce7f)

![Screenshot_20200806-191815_Tari Aurora.jpg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/88d9ecf4-b27d-4e52-b806-924e3c078b54)

![Screenshot_20200806-192058_Tari Aurora.jpg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/d7bcbea3-fc46-4294-a289-4ad7fd605324)
