### ISSUE TITLE
Giphy Integration - Core Functionality

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-android#502]
@talmahaj commented on [Wed Jul 22 2020](https://github.com/tari-project/wallet-android/issues/502)

We hypothesize that if we make transacting more fun, more people will want to tell others about Tari. Adding a fun factor to transactions also helps differentiate the Tari brand from that of other crypto projects, most of whom have apps that are quite dry and dull to use.

And since we already have emojis, the next most obvious "fun" thing to add is gifs. Several popular P2P payment apps outside the crypto space encourage fun metadata like images, emojis, gifs, and are not necessarily deemed any less trustworthy than their more bank-like competitors.

(After we launch the initial functionality, we'll explore enhancements like being able to intelligently generate gif suggestions based on the note text -- will mention in a separate ticket).

---

### *Docs*
https://developers.giphy.com/

### *Specs*

**Add a Note screen**
- Adding a note OR a gif should now be mandatory, but user does not need to add both in order for submit transaction button to become enabled.
- Each time screen is loaded, gif carousel should display random gifs from the "money" search query -  https://giphy.com/search/money
- User can only add one gif. Whenever a gif is selected, the gif carousel should slide down out of sight (and slide back up automatically if user removes the selected gif)
- Slide to Send button is now full-width and fixed to top of keyboard
- Tapping Search Giphy (either the fixed black button, or the last item in the carousel) brings up full-screen search. Tapping outside of the search modal or grabbing drawer should close modal and does not need to preserve search query in case user opens it up again - they can see the default again
- JUL 30 EDIT: Cropping gifs to match design rather than using default module is now out of scope for this ticket
- JUL 30 EDIT: slide to send should sit at the bottom of the screen if keyboard is collapsed
- AUG 05 EDIT: we can have the "Powered by giphy" on the add note screen and remove it everywhere else, we don't need to show it on the transaction list or detail page. 

**Transaction List screen** 
- If a transaction doesn't have a note attached, only a gif, just collapse the row where the note would've appeared so there isn't extra empty whitespace
- gif should always show in full height (but fixed width per design mockups) in feed

**Transaction Detail screen** (not included in design files)
- We do not have a mockup of this in Zeplin, but gif should show be at full height and fixed width such that it is flush on the left and right with the other content on the screen (that is, the same width as the white status bar, the grey divider, etc.)
- JUL 30 EDIT: Remove transaction ID from bottom of screen
- JUL 30 EDIT: Make screen scrollable to account for extra vertical space needed when there is a gif

**Case Handling**
- JUL 31 EDIT: If gif fails to load on tx list OR tx detail screen, show the gif failed state with a retry button (@karim-tari to provide design). When user taps retry button, gif returns to loading state until success or failure.
- JUL 31 EDIT: While gif is loading, display loading state (@karim-tari to provide design)

**Comment by talmahaj** [comment]
Please see responses to Jason's questions below:

"Where does the slide to send sit when the keyboard is dismissed?"
slide to send would sit at the bottom of the screen, right @karim ?

"Should we be hiding the giphy carousel when keyboard is dismissed? I considered finding a way to not allow them to drop the keyboard but we might have an issue on small phones."
I think we can just keep the carousel, seems like an edge case honestly (i agree with you about disabling it if it were easily possible but nbd)

"Can’t seem to find a way to limit the default “money” gifs and add the grey “Search giphy” block at the end of the carousel. It has infinity scrolling. The top left black button works fine."
It's cool, shouldn't be a big deal!

**Comment by talmahaj** [comment]
Also the following edits have been made to the original description:

**Add a Note screen**
- JUL 30 EDIT: Cropping gifs to match design rather than using default module is now out of scope for this ticket
- JUL 30 EDIT: slide to send should sit at the bottom of the screen if keyboard is collapsed

**Transaction Detail screen**
- JUL 30 EDIT: Remove transaction ID from bottom of screen
- JUL 30 EDIT: Make screen scrollable to account for extra vertical space needed when there is a gif

**Comment by talmahaj** [comment]
**Case Handling**
- JUL 31 EDIT: If gif fails to load on tx list OR tx detail screen, show the gif failed state with a retry button (@karim-tari to provide design). When user taps retry button, gif returns to loading state until success or failure.
- JUL 31 EDIT: While gif is loading, display loading state (@karim-tari to provide design)

**Comment by Tas4tari** [comment]
@talmahaj @kukabi @Anziskavds Test cases have been scripted for GIPHY Integration, please have a look and let me know if there are any edge cases etc that may have been overlooked:
[GIPHY Integration.pdf](https://github.com/tari-project/wallet-android/files/5017758/GIPHY.Integration.pdf)

**Comment by Tas4tari** [comment]
**Note screen:**
- Aug 5 EDIT: we can have the "Powered by giphy" on the add note screen and remove it everywhere else, we don't need to show it on the transaction list or detail page.  Added to the description above

**Comment by Anziskavds** [comment]
Tested successfully on Android on version 0.4.0 on a Samsung S9.

Test Report: https://big-neon.ontestpad.com/script/257/report

Screenshots:

![Screenshot_20200806-144227_Tari Aurora.jpg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/d9dca520-0285-4a77-bbce-b8112c80d006)

![Screenshot_20200806-151222_Tari Aurora.jpg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/5566a2b6-9411-4fe3-89c8-5d8e4f4d688f)


![Screenshot_20200806-152355_Tari Aurora.jpg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/6fd3644c-1bf8-415b-a539-d494c07e7132)

![Screenshot_20200806-152036_Tari Aurora.jpg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/fa4b3da3-bf41-42e5-876b-8f1513aec66a)

![Screenshot_20200806-152001_Tari Aurora.jpg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/d9d7649b-1196-4843-87c1-6cd9d51c04b2)

![Screenshot_20200806-150541_Tari Aurora.jpg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/e3b6d840-3a74-40af-8dd7-a5f92686902f)

![Screenshot_20200806-151206_Tari Aurora.jpg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/4ca7fb9d-5057-422f-befa-9e668a53f8d7)

![Screenshot_20200806-151954_Tari Aurora.jpg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/635b9af4-803e-482d-912d-5c1a49f74e3c)

![Screenshot_20200806-144137_Tari Aurora.jpg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/6c714fd5-a772-4425-b13b-6cf21e750138)

![Screenshot_20200806-150326_Tari Aurora.jpg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/201f5243-5ff6-46e4-b70d-89a53e357079)

![Screenshot_20200806-151257_Tari Aurora.jpg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/b417aae4-2de5-4268-af6f-6536eb1d4061)

![Screenshot_20200806-153526_Tari Aurora.jpg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/c2727b72-711d-4af6-aa9a-da084cf52b3a)

![Screenshot_20200806-152030_Tari Aurora.jpg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/aca2dea7-19e2-413c-abf4-7a9c30af470c)

![Screenshot_20200806-150354_Tari Aurora.jpg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/dc0afceb-5024-4ac5-95a5-9a48d81b9484)

![Screenshot_20200806-144218_Tari Aurora.jpg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/27efdf6a-381b-4b77-9825-01667b27af84)

![Screenshot_20200806-152123_Tari Aurora.jpg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/7467f5ee-d63b-40a1-95db-5029b44634b6)

![Screenshot_20200806-144311_Tari Aurora.jpg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/b11bc0eb-0c62-4edd-a11f-357f8dfef6ad)
