### ISSUE TITLE
Scheduled Backups: Backup does not seem to update immediately

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-android#509]
**Description:**
User schedules a backup and then switches off internet before the backup occurs.

**What happened:**

- User receives a push notification when the backup was scheduled to happen alerting them that the backup was not successful.
- User switched on Internet and navigated to Setting screen:
- Backups updated to "Up to date" status however the Last successful backup time was incorrect
- When user navigated out and then back to the Settings screen, after a few minutes the status displayed as Scheduled again (If the backup had completed then the status would have stayed as Up to Date)
- Also seems like after the initial scheduled status is displayed correctly, the second Scheduled status does not appear as per the design

**Video will display exactly what happens:**
https://drive.google.com/file/d/1ibvpi-1dS9eh2A234LD3FTT1nGfaDWS3/view?usp=sharing

**Comment by kukabi** [comment]
@Tas4tari When a scheduled backup fails the app retries twice to complete the backup, and if those fail too then the backup status is "Out of Date". If you visit the Settings or Backup Settings screens after a failure (provided there's no backup scheduled in the meanwhile) they should both be "Out of Date" status. At this moment you can trigger a backup by clicking "Backup Now", or another backup could be scheduled by a transaction event. This fix is in the latest release.

**Comment by Tas4tari** [comment]
Tested via the Regular release apk, on Huawei P30 Lite
Status shows as per scenario stated above by @kukabi and when user triggers a backup via the backup now feature, the backup is successful and backup time shows correctly. https://drive.google.com/file/d/19T0TCKIrwUW8kePPSN1ej4R5DXd2_VyC/view?usp=sharing

**Comment by Tas4tari** [comment]
**Tested successfully on the Beta release:** https://drive.google.com/file/d/1BVcAQUkGprXq7WZtNxHhUcwBOcYMfhuc/view?usp=sharing
