### ISSUE TITLE
Update tx list timestamp in real time

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-android#517]
Per the tx redesign tweaks ticket #488 there is now a "[#min]m ago" timestamp for txs initiated in the past hour. However, the number of minutes does not dynamically update in real time.

**Acceptance Criteria**
- the number of minutes displayed in the UI should dynamically increment by 1 minute every minute to always show the accurate # of minutes since the tx was initiated -- even if user keeps the tx list screen in the foreground

**Comment by Anziskavds** [comment]
Tested successfully on Android on version 0.4.0 on a Samsung S9.

![Screenshot_20200806-190703_Tari Aurora.jpg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/38bf16fd-8684-4016-ab60-cde1735fb699)

![Screenshot_20200806-190726_Tari Aurora.jpg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/4403fd6a-6d2e-4d21-84b1-a3e76175797c)

![Screenshot_20200806-190718_Tari Aurora.jpg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/ceb11798-d149-42f0-87bc-e32d27314188)

![Screenshot_20200806-190613_Tari Aurora.jpg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/f5850da0-bfd5-41c7-9dda-c3f2fa1f9458)
