### ISSUE TITLE
_JNIEnv::ReleaseStringUTFChars error on Android 11

### ISSUE THREAD

**Issue by kukabi** [tari-project/wallet-android#523]
https://sentry.tarilabs.com/organizations/sentry/issues/202/?project=2

**Comment by Tas4tari** [comment]
Testing regular release apk: v0.4.0 on browser-stack
Device: Pixel 4
OS: Android 11
 cc @kukabi @nyarian 
**Use Cases:**

- User can create a wallet
- User can navigate between: Home, Transaction List screen, Transaction Details screen, TTL Store, Profile screen, Home screen, Send transaction screen
- User can send a transaction
- User can save a contact

**Comment by Tas4tari** [comment]
Tested successfully, app no longer crashes on Create Wallet screen and user is able to navigate between screens, as well as Send and receive tXTR
