### ISSUE TITLE
Add GIF to the transaction details screen and make content scrollable

### ISSUE THREAD

**Issue by kukabi** [tari-project/wallet-android#524]
We should add the transaction GIF at the bottom of the content, remove the transaction id label and make the content below the top header section scrollable for possibly overflowing content.

**Comment by Tas4tari** [comment]
Tested on Beta build: v0.4.0 on Huawei P30 Lite by adding a very long note and a GIF. User can scroll to the bottom of the page to view the GIF and the transaction ID is no longer displayed within the TDS cc @kukabi 
**Video:**
https://drive.google.com/file/d/1fS7CwMd7AbPadQu68FvV8xzc3Cgdeysg/view?usp=sharing
