### ISSUE TITLE
Wallet info (profile) screen looks different than original design - match iOS

### ISSUE THREAD

**Issue by kukabi** [tari-project/wallet-android#525]
Android
![Screenshot_20200803-102330_Tari Aurora](https://user-images.githubusercontent.com/2969501/89164690-113d9480-d580-11ea-8d2e-e007755a877b.jpg)

iOS
![IMG_E8551](https://user-images.githubusercontent.com/2969501/89164705-17337580-d580-11ea-8c41-941c9e75a723.JPG)

**Comment by Tas4tari** [comment]
Tested successfully on App version: 0.4.0-jnLibs-0.16.0 on Huawei P30 Lite:
**Screenshot:**
![photo_2020-08-06 10 12 50](https://user-images.githubusercontent.com/50987039/89507948-805bf880-d7cd-11ea-84ef-f17535013678.jpeg)

**Comment by Tas4tari** [comment]
Profile screen on Private release also tested successfully and now matches iOS
