### ISSUE TITLE
GIPHY Integration: Search GIF screen is not as per design

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-android#543]
**Description:**
As a user I find that the Search GIF screen does not match the design on Android. The Search GIF screen on Android has the recipients contact name at the top (which does not appear on the design)

**Design:**
https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5f163cb0b53766827b06e0de

**Screenshot of what Android looks like:**
![photo_2020-08-11 08 17 41](https://user-images.githubusercontent.com/50987039/89863812-27b0a500-dbab-11ea-9c65-c32207c42a0d.jpeg)

**Comment by Tas4tari** [comment]
This issue requires custom component for GIPHY which is here: https://github.com/tari-project/wallet-android/issues/522 
Will move this to Up Next until the custom component is worked on

**Comment by Tas4tari** [comment]
@kukabi Moving this to Up Next

**Comment by kukabi** [comment]
@Tas4tari Thanks, yes, this view is from GIPHY SDK and we haven't yet been able to find a way to make it show full screen - it leaves a bit of gap at the top. And it looks to be by design on the screenshot at the top of the [GIPHY SDK page](https://developers.giphy.com/docs/sdk).

**Comment by Tas4tari** [comment]
Tested successfully on Huawei P30 Lite, app version 0.4.1
**Search screen matches the design on Zeplin:**
![photo_2020-08-31 12 12 16](https://user-images.githubusercontent.com/50987039/91709575-3aebda80-eb83-11ea-86f3-bbe099b0b9c4.jpeg)
![photo_2020-08-31 12 12 14](https://user-images.githubusercontent.com/50987039/91709586-3de6cb00-eb83-11ea-8b90-0481d73ca821.jpeg)

**User is also able to slide the drawer down:**
![photo_2020-08-31 12 12 54](https://user-images.githubusercontent.com/50987039/91709636-50610480-eb83-11ea-9dc2-748d57cf0234.jpeg)
