### ISSUE TITLE
Scanned QR-code address is ignored if the application and service were dead inbefore

### ISSUE THREAD

**Issue by nyarian** [tari-project/wallet-android#547]
Video journey: https://drive.google.com/file/d/1S2DfJUcKMkQPuECYoSqjhisb8CH1UYyv/view?usp=sharing

**Comment by Tas4tari** [comment]
Tested on Huawei P30 Lite by downloading the Regular release apk for version: 0.4.1
Tested by: 
Adding a URL with an emoji ID to the QR code generator and then scanning that code and ensuring the Send Tari screen on the app was opened.
**Tested the following scenarios:**

- App background process was running
- App background process was not running 

Both scenarios tested successfully

**Videos:**
**No background process running:** 
https://drive.google.com/file/d/1yrQ835n3guYRb5ZH-u7Dukn0oU5HEGxF/view?usp=sharing
**Background process running:**
https://drive.google.com/file/d/1Vmoo-xE_nrAa-9vu8jU_dEESIcRNhNl4/view?usp=sharing

@nyarian Quick question: With regards to the scenario where the app should not be running and the background process terminated, I see that when we enter the app via the deeplink, it displays the transaction list for about a second before transitioning to the Send Tari screen, is this correct? 
Video of this can be viewed from the links above

**Comment by Tas4tari** [comment]
@nyarian @kukabi Any response to the above question in the comment

**Comment by nyarian** [comment]
@Tas4tari yes that's correct, pages history should be in valid state (so that home page first and "send tx" page second) before transitioning

**Comment by Tas4tari** [comment]
@nyarian Thank you :) 
@kukabi @talmahaj As per the comment above, closing this issue
