### ISSUE TITLE
Base node setting is reset after closing Aurora

### ISSUE THREAD

**Issue by mikethetike** [tari-project/wallet-android#556]
Received via Marco on telegram. Is there a way to make my own base node setting permanent? After closing Aurora wallet, the entries are gone. :-(

Android 9

**Comment by nyarian** [comment]
@mikethetike the UI routine to change the base node is backed by direct invocation of `wallet_add_base_node_peer` function declared in `wallet.h`. Is it designed to be persisted by the wallet native library or the application itself should be responsible for this?

**Comment by CjS77** [comment]
I'd say store it in sharedPreferences and set it at startup

**Comment by philipr-za** [comment]
> I'd say store it in sharedPreferences and set it at startup. I'm pretty sure it's not persisted by wallet_ffi

This is correct, the backend does not persist the base nodes and expects them to be provided by the client after the backend is started up.

**Comment by kukabi** [comment]
We already store the base node in sharedPrefs, but the app doesn't restore the stored node at app startup, just picks a random node from our list.

If we should persist the base node, then we should also be able to delete the saved base node to go back to the provided list I think. It looks like we need the settings screen for the base node settings already, but as a temporary solution I'll just add some additional states/components to the existing base node settings screen. @CjS77 @talmahaj

**Comment by Tas4tari** [comment]
@kukabi Tested unsuccessfully on Huawei P30 Lite, app version 0.4.1
**Steps:**

- Log into app
- Check base node
- Force close the app
- Re-open the app
- Navigate to and check the base node

**Expected:**
Base node should not change

**What happened:**
Base node changed

**Video before closing the app**
https://drive.google.com/file/d/1guP1aDN-66mAttABUS-e-ZUjJ0NKi43g/view?usp=sharing

**Video after closing and re-opening the app:**
https://drive.google.com/file/d/1aKxJZXaV2FO0FvZOGJQjjf6sCFV4NQiM/view?usp=sharing

**Comment by Tas4tari** [comment]
Tested successfully on Huawei P30 Lite, app version 0.4.1
**When a custom BN was set:**
https://drive.google.com/file/d/1iuRoLZDLOLk_JowMzsuv20AgDKVLMKId/view?usp=sharing
**After user closed and re-opened:**
https://drive.google.com/file/d/1eQgasNbpdt5_OT2EBrIkWwn6QPkxUz65/view?usp=sharing
