### ISSUE TITLE
Cancelled transaction in transaction list should show cancelled status.

### ISSUE THREAD

**Issue by kukabi** [tari-project/wallet-android#558]
Currently a cancelled transaction only shows the amount pill in grey and no status is shown.

We should show the status field, the color should be same (orange) as the other statuses in transaction list (`Waiting for recipient...` etc).

**Comment by Tas4tari** [comment]
Tested successfully on Huawei P30 Lite, app version 0.4.1
**Screenshots:**
![photo_2020-08-31 12 00 11](https://user-images.githubusercontent.com/50987039/91708393-8a310b80-eb81-11ea-81ea-060e2cddf26f.jpeg)
![photo_2020-08-31 12 00 26](https://user-images.githubusercontent.com/50987039/91708411-92894680-eb81-11ea-9210-4557ff0770d7.jpeg)
