### ISSUE TITLE
Transaction details status text color should be as in design.

### ISSUE THREAD

**Issue by kukabi** [tari-project/wallet-android#559]
0.4.0 still uses the purple from the old design. Updated design:

https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5f16762b5b45918c4c46ffb9

**Comment by Tas4tari** [comment]
**Steps:**

- Send a transaction
- Transaction should be In Progress
- Select the transaction
- User should be on Transaction Details screen
- View the the transaction status
- Verify the transaction status displays as Yellow as per the design: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5f16762b5b45918c4c46ffb9
- Once completed, verify transaction status no longer appears on the transaction details screen

**Comment by Tas4tari** [comment]
Tested successfully on Huawei P30 Lite, app version 0.4.1
Status bar text on the Transaction Details screen appears as per the design linked above:

**Screenshot:**
![photo_2020-08-27 15 54 38](https://user-images.githubusercontent.com/50987039/91451364-a1b87d80-e87d-11ea-901a-292b44117f03.jpeg)

**Comment by Tas4tari** [comment]
Tested successfully on Huawei P30 Lite, app version 0.4.1
**Waiting for recipient come online:**
![photo_2020-08-31 11 57 52](https://user-images.githubusercontent.com/50987039/91708168-39211780-eb81-11ea-8423-de4479ee28b5.jpeg)
![photo_2020-08-31 11 57 49](https://user-images.githubusercontent.com/50987039/91708178-3b837180-eb81-11ea-9732-3f0a5b477188.jpeg)
