### ISSUE TITLE
Search GIPHY dialog background overlay should fade in when opening

### ISSUE THREAD

**Issue by kukabi** [tari-project/wallet-android#587]
Opening and closing sequences should be opposites.

![Screen Shot 2020-08-31 at 14 43 27](https://user-images.githubusercontent.com/2969501/91716611-ae4c1700-eb98-11ea-89a7-0d7c1a0dd631.png)

**Comment by Tas4tari** [comment]
Tested on Huawei P30 Lite, app version 0.4.1
The search screen slides up from the bottom and the user can slide the search screen down via the drawer to close this

**Video:**
https://drive.google.com/file/d/1EZgnWZy7KrwtYKsG4lT1OEJZXEq0ttIN/view?usp=sharing
