### ISSUE TITLE
Remove the GIF placeholder from the transaction view inside the transaction list.

### ISSUE THREAD

**Issue by kukabi** [tari-project/wallet-android#591]
Placholder should not display, and the GIF with correct height should be displayed once the download completes.

**Comment by Tas4tari** [comment]
Tested successfully using Huawei P30 Lite, app version 0.4.1.

**Comment by Tas4tari** [comment]
Tested successfully using Huawei P30 Lite, app version 0.4.1
**Screenshot:**
![photo_2020-09-07 10 51 08](https://user-images.githubusercontent.com/50987039/92368593-37fb6780-f0f8-11ea-9270-ef5f2b94b158.jpeg)

**Comment by Anziskavds** [comment]
Tested on Android on version 0.4.1 on a Samsung S9. 

@kukabi @Tas4tari @nyarian Is this what it should look like?

![Screenshot_20200907-110635_Tari Aurora.jpg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/e0e904c5-7e64-4c35-876d-8e8b38ee84bc)

**Comment by Tas4tari** [comment]
@Anziskavds Nope, that placeholder tile should not be there, you can look at the screenshot in my above comment to see what it looks like
