### ISSUE TITLE
User unable to back up to dry after resetting wallet

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-android#610]
**Description:**
Trying to backup my wallet to google drive (it worked previously before resetting my wallet) it says I am not signed into Google drive.

Maybe it's because I have two accounts on my phone?

**Expected Result:**
backed up to my personal drive.

**Actual Result:**
says I'm not signed into Drive.

**User:**
Evan K Fris

**Medium Reported:**
Bug Reports

**Logs:**
[ffi_logs_96DE27F1FECF211DE4D00A44CD9B50ABDBC3EEE989FDE8BB55E893C46B105723.zip](https://github.com/tari-project/wallet-android/files/5564816/ffi_logs_96DE27F1FECF211DE4D00A44CD9B50ABDBC3EEE989FDE8BB55E893C46B105723.zip)

**Screenshots:**
![Screenshot_20201118-174549](https://user-images.githubusercontent.com/50987039/99629942-a25a4d80-2a41-11eb-830b-41d9797fa990.png)
![Screenshot_20201118-174557](https://user-images.githubusercontent.com/50987039/99629950-a5edd480-2a41-11eb-9dc0-9022ae6bb457.png)

**Comment by alexandrVakhtinTari** [comment]
Solved
