### ISSUE TITLE
[Feature] Sending Tari: Adding a recipient by QR Code

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-android#70]
@talmahaj commented on [Fri Jan 10 2020](https://github.com/tari-project/wallet-ios/issues/88)

See [parent](https://github.com/tari-project/tari/issues/1174)

TODO:
[ ] Re-enable QR scanning in "Send To" screen. ![Screenshot 2020-02-19 at 14 15 24](https://user-images.githubusercontent.com/7573551/74833553-5cd9ea00-5322-11ea-94b7-c3918ec77963.png)
[ ] Parse the JSON and paste the emoji ID into the text view. 

Notes: 

1. Not for MVP, but on scanning a code, we'll want to provide an alias for the emoji ID and save it to the contact list.
2. The exact JSON format is not 100% finalised, but it's currently as follows:
```json
{ 
  "public_key": "64 char hex string",
  "emoji_id": "12 char emoji string",
}
```
The app should use the FFI to confirm that the public key and emoji Id match before pasting the emoji Id into the text view.

**Comment by CjS77** [comment]
The QR code scanning is complete.

We just need to tie the logic up into the transaction flow to close this out.
