### ISSUE TITLE
[Feature] Wallet Info/Profile

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-android#74]
@talmahaj commented on [Fri Jan 10 2020](https://github.com/tari-project/wallet-ios/issues/94)

See [parent](https://github.com/tari-project/tari/issues/1179)

**Comment by CjS77** [comment]
@jigneshsanghani - sorry about the confusion, but hopefully we're stabilising now. 
https://github.com/tari-project/tari/issues/1179 has been updated to describe what needs to be encoded into the QR
