### ISSUE TITLE
Implement a "dark" color palette

### ISSUE THREAD

**Issue by TruszczynskiA** [tari-project/wallet-android#794]
The new "dark" color palette was integrated into the app.

**Comment by EmmanuelDav** [comment]
Give more details on this issue

**Comment by TruszczynskiA** [comment]
Hi @EmmanuelDav 
I'm sorry to say that, but this task is a part of a bigger story currently being implemented by @alexandrVakhtinTari . 
But, if you still want to help us, then there is a task where we should align the app with one of the RFCs. If you're interested, just give me a sign, and I'll add all the necessary details to the task description.

**Comment by EmmanuelDav** [comment]
Apologies for the late reply, I would love to help @TruszczynskiA
