### ISSUE TITLE
[Feature] New user - Local authentication prompt screen

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-android#81]
@talmahaj commented on [Sun Jan 19 2020](https://github.com/tari-project/wallet-ios/issues/100)

See [parent](https://github.com/tari-project/tari/issues/1217)

**Comment by CjS77** [comment]
@talmahaj How should [this description](https://github.com/tari-project/tari/issues/1217) be adapted for Android?

Provide a prompt to say, "We want your wallet funds to be safe. Do you want to require fingerprint authentication every time the app comes into the foreground?"
And "Yes, secure my wallet", "No, I'll risk it" as the two buttons.

Obviously, the choice will set whether biometric auth is required going forward or not.

**Comment by talmahaj** [comment]
@CjS77 I'm not sure I follow -- why would the entire description change rather than just the lock screen type per 4.ii? @kukabi too

**Comment by CjS77** [comment]
Ok, I see; I misunderstood 4.ii on first read.

Ok, so to be clear, on Android --
