### ISSUE TITLE
When connecting a yat, the partner URL should specify 0x103, not 0x101

### ISSUE THREAD

**Issue by CjS77** [tari-project/wallet-android#883]
When specifying yat connections, a url endpoint like https://y.at/partner/aurora/manage?addresses=0x0101=C067AB898026F945CC63AB65A76F82A8711720BD3C3D0EAF1F9320E8F4C280A8D is executed.

The address tag should be `0x0103`, not `0x0101`

**Comment by TruszczynskiA** [comment]
Currently the callback from this endpoint is broken: 
- The hostname is invalid  - It's probably hardcoded as `y.at`, so the custom service instances that use a different host name doesn't work.
- The callback url (deeplink) have too many query separators (question marks). Expected one but deeplink have two.

**Comment by Krakaw** [comment]
> 
 * Hostname is flexible, but is currently set to tari://y.at
 * The extra `?` has been removed as seen in the below screenshot.
![image](https://github.com/tari-project/wallet-android/assets/41575888/b9a0b0ea-9371-4053-a98e-5e873cd128d8)
