### ISSUE TITLE
Bluetooth settings not identified correctly

### ISSUE THREAD

**Issue by CjS77** [tari-project/wallet-android#965]
**Device:** Google Pixel 6
**Android version**: 13

#### To replicate:
1. Tap on central profile icon
2. Tap BLE button

This dialog pops up:

![Screenshot_20230823-103106.png](https://github.com/tari-project/wallet-android/assets/7573551/051f815c-79b0-4e5d-9336-19f928645e3e)

3. Go to app permissions. Device discover _is_ enabled for this app:

![Screenshot_20230823-103121.png](https://github.com/tari-project/wallet-android/assets/7573551/da868785-3e32-4d26-9efb-d638b260ed95)

**Comment by alexandrVakhtinTari** [comment]
Fixed in current release
