### ISSUE TITLE
Incorrect block explorer linked

### ISSUE THREAD

**Issue by CjS77** [tari-project/wallet-android#981]
In transaction view, tapping "View on the block explorer" opens the wrong explorer

* Tari explorers are named `explore-{network}.tari.com`
* Aurora is selected for Stagenet
* Therefore the correct block explorer is `explore-stagenet.tari.com` (as of 19/9/23, this domain is invalid)
* ..or `textexplore-stagenet.tari.com`
* It's currently linking to esme's eplorer

**Comment by TruszczynskiA** [comment]
The buttons are now hidden. It will be shown again when the new version of the block explorer will be done.
